### PR TITLE
[Do not merge] Create WFs long names to short name links

### PR DESCRIPTION
**Pull request by smuzaffar**
This is to test the workflows short names proposed in https://github.com/cms-sw/cmssw/pull/40106

### CODE REVIEW

**Comment by smuzaffar** [comment]
@vlimant , looks like https://github.com/cms-sw/cms-bot/blob/dbed14e6dd4a8579973cf33f77035ea72d94c8c8/logRootQA.py#L326 check if hoing to fail for short wf names. Should we remove the `('PU' in r or 'RECODR' in r or 'REMINIAOD' in r)` condition ?

**Comment by smuzaffar** [comment]
also looks like logs files names needs to be updated too. Currently https://github.com/cms-sw/cms-bot/blob/dbed14e6dd4a8579973cf33f77035ea72d94c8c8/logRootQA.py#L290 is not going to find command long files. I guess I can also rename the logs

**Comment by vlimant** [comment]
indeed there are issues in `logRootQA.py` and the log files are very different indeed

**Comment by vlimant** [comment]
looks like very cumbersome to allow for Half changed directory names. would there be a way to produce a baseline with [#](https://github.com/cms-sw/cmssw/pull/40106) in and pull this in for the PR testing

**Comment by smuzaffar** [comment]
@vlimant , I can fix the log file names here. Renaming the log file names and workflow dirs names are only needed for testing the change in https://github.com/cms-sw/cmssw/pull/40106 . Once #40106 is merged and a new baseline with is available then there is no need for renaming logs/wf dirs. I am more worried about https://github.com/cms-sw/cms-bot/blob/dbed14e6dd4a8579973cf33f77035ea72d94c8c8/logRootQA.py#L326 which is not matching any root file now

**Comment by smuzaffar** [comment]
> would there be a way to produce a baseline with [#40106](https://github.com/cms-sw/cmssw/pull/40106) in and pull this in for the PR testing

No there is no way to generate baseline with #40106 but how about I just use #40106 result as baseline e.g. comparing #40106 with #40106 . No rename of file names will be needed :-)

**Comment by vlimant** [comment]
> > would there be a way to produce a baseline with [#40106](https://github.com/cms-sw/cmssw/pull/40106) in and pull this in for the PR testing
> 
> No there is no way to generate baseline with cmssw-/cmssw#40106 but how about I just use cmssw-/cmssw#40106 result as baseline e.g. comparing #40106 with #40106 . No rename of file names will be needed :-)

maybe #40106 as baseline and #40106+#40100 where a couple of changes are expected

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#40106,cms-sw/cmssw#40100

**Comment by smuzaffar** [comment]
@vlimant , latest change should use cms-sw/cmssw#40106 as baseline for pr tests of cms-sw/cmssw#40106 + cms-sw/cmssw#40100

**Comment by smuzaffar** [comment]
@vlimant , comparison with baseline of cms-sw/cmssw/#4016 look good. Only thing is that it only found `24 edm output root files` while with long workflow names it processs 48 edm root files

**Comment by vlimant** [comment]
what are those 48 ?

**Comment by vlimant** [comment]
it's the line `if ('PU' in r or 'RECODR' in r or 'REMINIAOD' in r) and 'inDQM.root' not in r:` that does not match as much as before

**Comment by vlimant** [comment]
we should try without it ; I don't think this will hurt

**Comment by smuzaffar** [comment]
> what are those 48 ?

these are
```
 find /cvmfs/cms-ci.cern.ch/jenkins-artifacts/ib-baseline-tests/CMSSW_12_6_X_2022-11-17-2300/el8_amd64_gcc10/-GenuineIntel/matrix-results -name 'step*.root' -type f | grep -v 'inDQM.root' | grep -E '(PU|RECODR|REMINIAOD)'  | rev | cut -d/ -f1,2 | rev
10224.0_TTbar_13+2017PU+TTbar_13TeV_TuneCUETP8M1_GenSim+DigiPU+RecoFakeHLTPU+HARVESTFakeHLTPU+Nano/step1.root
10224.0_TTbar_13+2017PU+TTbar_13TeV_TuneCUETP8M1_GenSim+DigiPU+RecoFakeHLTPU+HARVESTFakeHLTPU+Nano/step5.root
10224.0_TTbar_13+2017PU+TTbar_13TeV_TuneCUETP8M1_GenSim+DigiPU+RecoFakeHLTPU+HARVESTFakeHLTPU+Nano/step3.root
10224.0_TTbar_13+2017PU+TTbar_13TeV_TuneCUETP8M1_GenSim+DigiPU+RecoFakeHLTPU+HARVESTFakeHLTPU+Nano/step2.root
10224.0_TTbar_13+2017PU+TTbar_13TeV_TuneCUETP8M1_GenSim+DigiPU+RecoFakeHLTPU+HARVESTFakeHLTPU+Nano/step3_inMINIAODSIM.root
11834.0_TTbar_14TeV+2021PU+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoNanoPU+HARVESTNanoPU/step1.root
11834.0_TTbar_14TeV+2021PU+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoNanoPU+HARVESTNanoPU/step3_inNANOEDMAODSIM.root
11834.0_TTbar_14TeV+2021PU+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoNanoPU+HARVESTNanoPU/step3_inMINIAODSIM.root
11834.0_TTbar_14TeV+2021PU+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoNanoPU+HARVESTNanoPU/step3.root
11834.0_TTbar_14TeV+2021PU+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoNanoPU+HARVESTNanoPU/step2.root
13434.0_TTbar_14TeV+2021FSPU+TTbar_14TeV_TuneCP5_Gen+FastSimRun3PU+HARVESTFastRun3PU/step2_inMINIAODSIM.root
13434.0_TTbar_14TeV+2021FSPU+TTbar_14TeV_TuneCP5_Gen+FastSimRun3PU+HARVESTFastRun3PU/step1.root
13434.0_TTbar_14TeV+2021FSPU+TTbar_14TeV_TuneCP5_Gen+FastSimRun3PU+HARVESTFastRun3PU/step2_inNANOEDMAODSIM.root
13434.0_TTbar_14TeV+2021FSPU+TTbar_14TeV_TuneCP5_Gen+FastSimRun3PU+HARVESTFastRun3PU/step2.root
136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2_skimSinglePh/step3_inMINIAOD.root
136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2_skimSinglePh/step2.root
136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2_skimSinglePh/step3.root
136.7611_RunJetHT2016E_reminiaod+RunJetHT2016E_reminiaod+REMINIAOD_data2016_HIPM+HARVESTDR2_REMINIAOD_data2016_HIPM/step2.root
136.793_RunDoubleEG2017C+RunDoubleEG2017C+HLTDR2_2017+RECODR2_2017reHLT_skimDoubleEG_Prompt+HARVEST2017_skimDoubleEG/step3_inMINIAOD.root
136.793_RunDoubleEG2017C+RunDoubleEG2017C+HLTDR2_2017+RECODR2_2017reHLT_skimDoubleEG_Prompt+HARVEST2017_skimDoubleEG/step2.root
136.793_RunDoubleEG2017C+RunDoubleEG2017C+HLTDR2_2017+RECODR2_2017reHLT_skimDoubleEG_Prompt+HARVEST2017_skimDoubleEG/step3.root
136.8311_RunJetHT2017F_reminiaod+RunJetHT2017F_reminiaod+REMINIAOD_data2017+HARVEST2017_REMINIAOD_data2017/step2.root
136.874_RunEGamma2018C+RunEGamma2018C+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Offline_L1TEgDQM+HARVEST2018_L1TEgDQM/step3_inMINIAOD.root
136.874_RunEGamma2018C+RunEGamma2018C+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Offline_L1TEgDQM+HARVEST2018_L1TEgDQM/step2.root
136.874_RunEGamma2018C+RunEGamma2018C+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Offline_L1TEgDQM+HARVEST2018_L1TEgDQM/step3.root
136.88811_RunJetHT2018D_reminiaodUL+RunJetHT2018D_reminiaodUL+REMINIAOD_data2018UL+HARVEST2018_REMINIAOD_data2018UL/step2.root
139.001_RunMinimumBias2021+RunMinimumBias2021+HLTDR3_2022+RECODR3_reHLT_MinBiasOffline+HARVESTD2021MB/step3_inMINIAOD.root
139.001_RunMinimumBias2021+RunMinimumBias2021+HLTDR3_2022+RECODR3_reHLT_MinBiasOffline+HARVESTD2021MB/step3.root
139.001_RunMinimumBias2021+RunMinimumBias2021+HLTDR3_2022+RECODR3_reHLT_MinBiasOffline+HARVESTD2021MB/step2.root
158.01_HydjetQ_reminiaodPbPb2018_INPUT+HydjetQ_reminiaodPbPb2018_INPUT+REMINIAODHI2018PPRECOMB+HARVESTHI2018PPRECOMINIAOD/step2.root
21034.999_TTbar_14TeV+2026D88PU_PMXS1S2PR+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU/step1.root
21034.999_TTbar_14TeV+2026D88PU_PMXS1S2PR+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU/step4_inMINIAODSIM.root
21034.999_TTbar_14TeV+2026D88PU_PMXS1S2PR+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU/step2.root
21034.999_TTbar_14TeV+2026D88PU_PMXS1S2PR+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU/step4.root
21034.999_TTbar_14TeV+2026D88PU_PMXS1S2PR+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU/step3.root
250202.181_TTbar_13UP18+TTbar_13UP18+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25/step1.root
250202.181_TTbar_13UP18+TTbar_13UP18+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25/step4_inMINIAODSIM.root
250202.181_TTbar_13UP18+TTbar_13UP18+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25/step4.root
250202.181_TTbar_13UP18+TTbar_13UP18+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25/step3.root
250202.181_TTbar_13UP18+TTbar_13UP18+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25/step2.root
25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+NANOUP15/step1.root
25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+NANOUP15/step5.root
25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+NANOUP15/step3_inMINIAODSIM.root
25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+NANOUP15/step3.root
25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+NANOUP15/step2.root
4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT/step3_inMINIAOD.root
4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT/step2.root
4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT/step3.root
```

**Comment by smuzaffar** [comment]
> it's the line `if ('PU' in r or 'RECODR' in r or 'REMINIAOD' in r) and 'inDQM.root' not in r:` that does not match as much as before

If we try without this condition then logRootQA.py will process 158 root files (instead of 48) which can increase the processing time

**Comment by vlimant** [comment]
since the provenance was made for all outputs already, we could use that for selecting relevant `step*.root`. I am not even sure the current selection is fully relevant. Are we really interested in all 4

> 25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+NANOUP15/step1.root
> 25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+NANOUP15/step5.root
> 25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+NANOUP15/step3.root
> 25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+NANOUP15/step2.root

**Comment by vlimant** [comment]
@slava77 ; do you recall what that line in logRootQA.py is meant for ?

**Comment by slava77** [comment]
> @slava77 ; do you recall what that line in logRootQA.py is meant for ?

IIRC the idea was to parse only a representative set of wfs instead of all.

**Comment by vlimant** [comment]
> IIRC the idea was to parse only a representative set of wfs instead of all.

would it makes sense to use the same selection as in https://github.com/cms-sw/cms-bot/blob/master/comparisons/validateJR.py#L89 using the last process

**Comment by slava77** [comment]
> > IIRC the idea was to parse only a representative set of wfs instead of all.
> 
> would it makes sense to use the same selection as in https://github.com/cms-sw/cms-bot/blob/master/comparisons/validateJR.py#L89 using the last process

I think that the idea for logRootQA was to cover all logs in a wf. @davidlange6 I recall that you introduced it. Please comment if your recall the rationale.

**Comment by vlimant** [comment]
all logs are parsed ; no pb
we are wondering about the selection of root files to be passed to `checkResult=checkEventContent(baseDir+r,testDir+r)`

**Comment by slava77** [comment]
> we are wondering about the selection of root files to be passed to `checkResult=checkEventContent(baseDir+r,testDir+r)`

ah; I think that this one should cover all files as well. This is not just for reco.

**Comment by vlimant** [comment]
that's what I thought too. But ATM only files/directories that pass `if ('PU' in r or 'RECODR' in r or 'REMINIAOD' in r) and 'inDQM.root' not in r:` will be checked

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
I have updated the PR to run `edmEventSize` check for all root files ( except for `inDQM.root`) . Previously `logRootQA.py` took 20 mins to process all logs and selected root files. Lets see how much time it will take for all root files processing

[a]
```
13:08:31 + python3 /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/cms-bot/logRootQA.py /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/CMSSW_12_6_X_2022-11-23-2300 /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-7e9aa5 /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/JR-comparison /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/default-comparison
13:28:55 + grep -a SUMMARY /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/JR-comparison/logRootQA.log
```

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw/pull/40106,https://github.com/cms-sw/cmssw/pull/40100

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#40106,cms-sw/cmssw#40100

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw/pull/40106

**Comment by vlimant** [comment]
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_0_X_2022-11-28-1100+7e9aa5/54366/validateJR.html looks OK to me
@smuzaffar maybe we can get rid of the leading "/" ?

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw/pull/40106

**Comment by smuzaffar** [comment]
@vlimant , https://github.com/cms-sw/cms-bot/pull/1890#issuecomment-1331502544 looks good. Processing all root files (except for inDQM.root) for edmEventSize increases the comparison time by 30mins (logRootQA.py now takes 50mins instead of 20mins). I think for now this is good . 

How should we proceed with your https://github.com/cms-sw/cmssw/pull/40106 change? I can open a bot PR with https://github.com/cms-sw/cms-bot/pull/1890/commits/ffcf75edd684c1074e9f170251b618f699dc2e71 change to do the `long name` to `short name` mapping so that PR tests for cms-sw/cmssw#40106 do not see warnings message like
```
The workflows 4.53, 4.22, 2500.601, 158.01, 140.56, 140.53, 139.001, 138.5, 138.4, 136.88811, 136.874, 136.8311, 136.793, 136.7611, 136.731, 1001.0, 1000.0 have different files in step1_dasquery.log than the ones found in the baseline. You may want to check and retrigger the tests if necessary. You can check it in the "files" directory in the results of the comparisons
```

**Comment by smuzaffar** [comment]
We only needed https://github.com/cms-sw/cms-bot/commit/ffcf75edd684c1074e9f170251b618f699dc2e71 change for simple mapping. We have to keep this mapping in bot for a day so that all PR tests which use IBs with long names can still run a useful comparison job.

I will open a PR to automatically enable long to short name mapping if needed.

**Pull request closed without merging**
