### PR TITLE
allow Alberto Sanchez (GEN L3) to sign PR in CMSSW

### PR DESCRIPTION
**Pull request by perrozzi**

### CODE REVIEW

**Comment by smuzaffar** [comment]
+externals
@fabiocos , any objections?

**Comment by fabiocos** [comment]
@smuzaffar no, I suggested to have one more person in the generators area that could be mainly devoted to software scrutiny and help there

**Comment by efeyazgan** [comment]
Bur won't we have better covarage with 3 people (two l2 + integration convener) ?

**Comment by perrozzi** [comment]
(unless I did something wrong there are now 3 people able to sign GEN PR https://github.com/perrozzi/cms-bot/blob/54804be44ac829917e2d9daa5434562e8cdea80a/categories.py#L50-L52)

**Comment by fabiocos** [comment]
@efeyazgan @perrozzi exactly, now there are 3 people able to sign for GEN, so there is a bit less pressure on the L2 as also one L3 devoted to software can do it

https://cms-sw.github.io/categories.html

**Pull request merged**
