### PR TITLE
New ECAL DPG convener: Jin Wang

### PR DESCRIPTION
**Pull request by simonepigazzini**
- removing Shilpi and Simone

### CODE REVIEW

**Comment by simonepigazzini** [comment]
@thomreis

**Comment by smuzaffar** [comment]
@jainshilpi and @wang0jin , any objections on this change?

**Comment by jainshilpi** [comment]
@smuzaffar this looks good to me. Thanks @simonepigazzini for the update.

**Comment by perrotta** [comment]
merge

**Pull request merged**
