### PR TITLE
Add generation of igprof memory profile report for pull requests

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
please test with cms-sw/cmssw#34908 cms-data/RecoEgamma-ElectronIdentification#22

**Comment by smuzaffar** [comment]
enable profiling

**Comment by smuzaffar** [comment]
please test

**Comment by gartung** [comment]
@smuzaffar Can this be merged?

**Comment by smuzaffar** [comment]
please test
lets re-run the tests. I wanted to see the effect of new profile report

**Pull request merged**
