### PR TITLE
Move to slc7_amd64_gcc530 as production arch for CMSSW_8_0_36_patch1

### PR DESCRIPTION
**Pull request by smuzaffar**
see https://github.com/cms-sw/cmssw/issues/36708
FYI @qliphy @perrotta @cms-sw/pdmv-l2

### CODE REVIEW

**Comment by smuzaffar** [comment]
By the way, I see that `CMSSW_8_0_34_UL` was build for slc7_amd64_gcc530. Are we sure that we want CMSSW_8_0_36+patch or CMSSW_8_0_34_UL + patch

**Comment by jordan-martins** [comment]
> 

hi guys, I would say that this is the best... we could have the 36_patch1 with slc6 and use in the 8_X MC Campaigns and have another one with UL (8_0_35_UL) that go under slc7... what do u think?

**Comment by qliphy** [comment]
> @qliphy , see [cms-sw/cmssw#28655](https://github.com/cms-sw/cmssw/issues/28655) . May be we should build CMSSW_8_0_36_UL for slc7_amd64_gcc530?

@smuzaffar   I found 8_0_34 is identical as 8_0_34_UL,  except the former for slc6 while the latter for slc7.   However,for 8_0_35 and above, only non-UL release was built,  and the releases supports both slc6 and slc7.

That is why I think we should just build 8_0_36_patch1 instead of 8_0_36_UL  (we don't have 8_0_35_UL).  What do you and others think?

**Comment by smuzaffar** [comment]
@qliphy  , looks like slc6 8_0_X is used for MC Campaigns so changing the production arch to slc7 might have a big impact there.

**Comment by qliphy** [comment]
> hi guys, I would say that this is the best... we could have the 36_patch1 with slc6 and use in the 8_X MC Campaigns and have another one with UL (8_0_35_UL) that go under slc7... what do u think?

Ok,  seems good to have  8_0_36_patch1 with slc6 for 8_X MC, and 8_0_35_UL (or 8_0_36_UL?) with slc7 for UL.

**Comment by qliphy** [comment]
> @qliphy , looks like slc6 8_0_X is used for MC Campaigns so changing the production arch to slc7 might have a big impact there.

Right.  I agree.  Then let's close this PR. 
And I will launch the build of  CMSSW_8_0_36_UL for slc7_amd64_gcc530 following  cms-sw/cmssw#28655 
BTW: @smuzaffar  should it be CMSSW_8_0_36_UL or CMSSW_8_0_35_UL?

**Comment by smuzaffar** [comment]
clean solution would be that we build 
- CMSSW_8_0_36_UL for slc7 using CMSSW_8_0_36 tag ( just to be consistent with CMSSW_8_0_34_UL naming )
- CMSSW_8_0_36_UL_patch1 for slc7

what do you think?

**Comment by jordan-martins** [comment]
good from my side! :)

**Comment by qliphy** [comment]
Thanks @smuzaffar  Sounds good to me.  Let's do like this.  

Just to make sure, we will do two builds as following, right? :

1)   Build CMSSW_8_0_36_UL
CMSSW_COMMIT:CMSSW_8_0_36
ARCHITECTURE:slc7_amd64_gcc530
PRODUCTION_ARCHITECTURE:slc7_amd64_gcc530

2)  Build CMSSW_8_0_36_UL_patch1
ARCHITECTURE:slc7_amd64_gcc530
PRODUCTION_ARCHITECTURE:slc7_amd64_gcc530

**Comment by smuzaffar** [comment]
@qliphy , yes this is correct. I am closing this PR now

**Pull request closed without merging**
