### PR TITLE
Add rappoccio to ORP

### PR DESCRIPTION
**Pull request by rappoccio**

### CODE REVIEW

**Comment by perrotta** [comment]
@rappoccio I also added you to "operations": you will even be more entitled than us to sign for operations...

**Comment by perrotta** [comment]
+1

**Comment by smuzaffar** [comment]
@rappoccio , looks like you do not have 2FA enabled for github account.  As once you become member of ORP then you will become owner of `cms-sw` , `cms-data`, and `cms-externals` github organizations. So I would highly recommend to enable 2FA

**Comment by rappoccio** [comment]
@smuzaffar yes, good point. Done now.

**Comment by rappoccio** [comment]
Thanks @smuzaffar ! :)

**Pull request merged**
