### PR TITLE
reco comparisons new phase-2 wf numbering after reset around 2022-10-11

### PR DESCRIPTION
**Pull request by slava77**
- index reset was introduced in cms-sw/cmssw#39571 
- D94 workflows were added in cms-sw/cmssw#38702 , but I did not cover the old numbering variant

this should clear the warnings in the comparisons summaries

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cms-sw/upgrade-l2 @cms-sw/reconstruction-l2

**Comment by slava77** [comment]
> Comparison Summary

it looks like all 6 workflows for phase2 were recognized and comparisons directories with logs show up as expected.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
