### PR TITLE
New SimPPS/DirectSimProducer subpackage for simulation 

### PR DESCRIPTION
**Pull request by forthommel**
Adding `SimPPS/DirectSimProducer` to the `simulation` category, in line with https://github.com/cms-sw/cmssw/pull/38280

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
According to https://github.com/cms-sw/cms-bot/pull/1597#issuecomment-887354987 there is no need to test PRs like this one. Any objection @iarspider ?

**Comment by perrotta** [comment]
+orp

**Comment by iarspider** [comment]
> According to [#1597 (comment)](https://github.com/cms-sw/cms-bot/pull/1597#issuecomment-887354987) there is no need to test PRs like this one. Any objection @iarspider ?

No objections

**Comment by aandvalenzuela** [comment]
+1

**Comment by perrotta** [comment]
please abort

**Comment by aandvalenzuela** [comment]
Thanks @perrotta :)

**Comment by perrotta** [comment]
Sorry @aandvalenzuela: I think I have inadvertently started the tests with my "+1".
In this case, we should just write "merge" to merge it without testing (I should have known, but I just forgot it...)

**Comment by forthommel** [comment]
Many thanks to you all for this very fast reaction! :)
https://github.com/cms-sw/cmssw/pull/38280 is now (fortunately) one step closer to completion!

**Pull request merged**
