### PR TITLE
reco comparisons: add maps for Run3/2021 HI MC workflows

### PR DESCRIPTION
**Pull request by slava77**
added for wf 159.0, 311.0, and 312.0

the last one is needed in connection with cms-sw/cmssw#32025

### CODE REVIEW

**Comment by slava77** [comment]
@smuzaffar @mrodozov 
based on the tests, I think that this PR is good to be merged:
the new workflow added in cms-sw/cmssw#32025 was picked up correctly via the map file for  https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-11-04-1100+b3e122/39719/validateJR/

**Comment by smuzaffar** [comment]
@slava77 , what about the SiOuter Track comparison differences ? Are they expected?

**Comment by smuzaffar** [comment]
please test
just to see if comparsion changes are not elated to the change here

**Comment by slava77** [comment]
> @slava77 , what about the SiOuter Track comparison differences ? Are they expected?

interesting, but can not be related to changes in this PR

**Comment by makortel** [comment]
> what about the SiOuter Track comparison differences ? Are they expected?

They are compatible with https://github.com/cms-sw/cmssw/issues/31644

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
