### PR TITLE
Fix validate in 5.3

### PR DESCRIPTION
**Pull request by vlimant**
recent PR test in 5.3 failed.
this aim at fixing it by removing range based loops and enable from FWlite

### CODE REVIEW

**Comment by vlimant** [comment]
please test for CMSSW_5_3_X

**Comment by vlimant** [comment]
silly me, I forgot the `SetExponentOffset`

**Comment by vlimant** [comment]
please test for CMSSW_5_3_X

**Comment by smuzaffar** [comment]
please test
lets test for 12.6.X

**Comment by vlimant** [comment]
the log says 

> plotting variable: HBHEDataFramesSorted_simHcalDigis__RECO.obj.obj@.size()
> Error in <TTreeFormula::Compile>:  Bad numerical expression : "HBHEDataFramesSorted_simHcalDigis__RECO.obj.obj@.size()"
> Comparison died 

but that's because these were not available in 5.3 ; all good

**Comment by vlimant** [comment]
looks good!

**Comment by smuzaffar** [comment]
+externals
looks good, we can also avoid the warnings [a] in a different PR.

[a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_6_X_2022-11-22-1100+d61262/54244/validateJR/validateJR.log
```
WARNING: AutoLibraryloader::enable() and AutoLibraryLoader.h are deprecated.
Use FWLiteEnabler::enable() and FWLiteEnabler.h instead
```

**Pull request merged**
