### PR TITLE
add Jean-Roch and Sebastian as new XPOG.

### PR DESCRIPTION
**Pull request by vlimant**
please consider this PR to add the new XPOG officers to signatures.

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
+1
- I don't think we need to test it either

**Comment by aandvalenzuela** [comment]
please abort

**Comment by aandvalenzuela** [comment]
@perrotta It seems I can also start the tests with `+1`

**Comment by perrotta** [comment]
> @perrotta It seems I can also start the tests with `+1`

Yes, every "+1" can start them, if not already done. 
Let just merge it

**Comment by perrotta** [comment]
merge

**Pull request merged**
