### PR TITLE
enable code-format for latest releases with new config_tag

### PR DESCRIPTION
**Pull request by smuzaffar**
@fabiocos , this should enable code-format for latest release cycles.

### CODE REVIEW

**Comment by fabiocos** [comment]
@smuzaffar thanks, this will be anyway active only for PRs in the master branch, right? There is no code-checks enables for older cycles. Everything is now driven by $CMSSW_BASE/config/config_tag, this is the tag of the used snapshot of https://github.com/cms-sw/cmssw-config right?
What I do not understand is the master version of the SCRAM setup needs to be merged if the tag is up to date. For any tag posterior in sync with master this should be useless, am I correct?

**Comment by smuzaffar** [comment]
@fabiocos , yes code-checks only runs by default for master branch but one can explicitly run it for non-master branch by issuing `code-checks` comment.
This change will allow to run `code-format` for old release cycles if config_tag is correct. For example when we have CMSSW_11_1_X or CMSSW_12_0_X then we still want to keep running (of course on demand only) code-format for CMSSW_11_0_X ... right?

**Comment by fabiocos** [comment]
@smuzaffar ok, I get the point. If we want to keep the possibility to run the procedure on older releases I see the logic of the code. Of course doing it now will force clang-format on older code, so one should be even more careful in doing so.

**Comment by smuzaffar** [comment]
+externals
This has been tested for https://github.com/cms-sw/cmssw/pull/27225

**Comment by smuzaffar** [comment]
@fabiocos , feel free to merge. As soon it is merged code-format will be enabled for PR

**Comment by fabiocos** [comment]
+1

**Pull request merged**
