### PR TITLE
update JME L2s

### PR DESCRIPTION
**Pull request by kirschen**
Christine left CMS, Alexis and Mikko incoming

### CODE REVIEW

**Comment by smuzaffar** [comment]
thanks @kirschen . There was no need to update [cmssw_l2/l2.json](https://github.com/cms-sw/cms-bot/pull/1761/files#diff-c7e2862bfe670716a6c4cdbb62c29971518852e39ab8dd5bf1be36e389a301a4)  , this is automatically updated by bot

**Comment by jpata** [comment]
>  this is automatically updated by bot

It was my suggestion, I didn't know. Noted for the future.

**Comment by kirschen** [comment]
> thanks @kirschen . There was no need to update [cmssw_l2/l2.json](https://github.com/cms-sw/cms-bot/pull/1761/files#diff-c7e2862bfe670716a6c4cdbb62c29971518852e39ab8dd5bf1be36e389a301a4) , this is automatically updated by bot

Hi @smuzaffar ! Thanks and understood, the automatic setup makes a lot of sense, happy to edit one file less :-)
Just noticed that Christine is still/again in the l2.json, you might want to remove her, but otherwise all looking good to me.

**Comment by smuzaffar** [comment]
> > thanks @kirschen . There was no need to update [cmssw_l2/l2.json](https://github.com/cms-sw/cms-bot/pull/1761/files#diff-c7e2862bfe670716a6c4cdbb62c29971518852e39ab8dd5bf1be36e389a301a4) , this is automatically updated by bot
> 
> Hi @smuzaffar ! Thanks and understood, the automatic setup makes a lot of sense, happy to edit one file less :-) Just noticed that Christine is still/again in the l2.json, you might want to remove her, but otherwise all looking good to me.

this is fine, this is how bot keep tracks of L2's and their github comments/commands.

**Pull request merged**
