### PR TITLE
Syncronize github_webhook with cmssdt-web/cgi_bin/github_webhook and make Python 3 compatibility changes.

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by gartung** [comment]
Accidentally pushed branch with FNAL updates.

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
@mrodozov @gudrutis @smuzaffar How is GITHUB_WEBHOOK_TOKEN generated from the secret used for the github webhook?

**Comment by gartung** [comment]
It looks like this might be it:
https://github.com/cms-sw/cms-bot/blob/ba1930e6126d9a104a2786f69e16924adab159bf/create-github-hooks#L119

**Comment by gartung** [comment]
I found it 
https://github.com/cms-sw/cmssdt-web/blob/22226b5c05d6eefaa9c73a4d83d364cbfc3a99cc/cgi-bin/encrypt_github_token#L7

**Comment by gartung** [comment]
OK. Should I submit a PR to cmssdt-web with the updated github_webhook?

**Comment by smuzaffar** [comment]
@gartung , yes please submit PR fr cmssdt-web.

**Pull request merged**
