### PR TITLE
add PAT packages to XPOG category

### PR DESCRIPTION
**Pull request by vlimant**
maybe not to be merged right away. there could be other packages falling in the MINIAOD category that xpog could be asked to review

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
please abort

- There is no need to test changes in `categories_map.py`

**Comment by aandvalenzuela** [comment]
Hi @vlimant, can I merge this one (and then we can continue with a follow-up PR in case more packages need to be reviewed)? Or do you prefer to wait?

Thank you,
Andrea.

**Comment by vlimant** [comment]
sounds good

**Pull request merged**
