### PR TITLE
Build 7_6_X with gcc493 branch and off slc6_amd64_gcc493 arch.

### PR DESCRIPTION
**Pull request by degano**

### CODE REVIEW

**Comment by degano** [comment]
@smuzaffar Is this okay? Shall we merge it?

**Comment by smuzaffar** [comment]
looks good

**Comment by ktf** [comment]
May I ask what is the reason for CMS to move to gcc 4.9.3?

**Comment by davidlt** [comment]
We are  compilers erros in GEANT4 IIRC.

**Comment by ktf** [comment]
@dberzano let's keep this in mind..

**Comment by davidlt** [comment]
@degano why do we need a branch for 3 line change? Why not to applied that to `IB/CMSSW_7_6_X/stable`?

If you introduced a new default branch for `CMSSW_7_6_X`, have you also modified the rules how _CMSDIST_ branches are updated?

**Comment by davidlt** [comment]
Ah, I guess you keep _stable_, because you are not changed other CMSSW builds to GCC 4.9.3 yet.

**Comment by degano** [comment]
@davidlt Exactly, the plan is to build 7_6_0_pre2 both on gcc491 and gcc493.
Once that'll be done I'll merge it to stable and delete the gcc493 branch.

**Pull request merged**
