### PR TITLE
Enable PR GPU comparisons

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
enable gpu

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@slava77 , this PR should enable comparison for GPU workflows . The PR comment summary will look like this https://github.com/cms-sw/cms-bot/pull/1521#issuecomment-807872515 . As CPU workflows and GPU workflows runs of different machines , so there is no easy way to combine the comparisons. If this looks good then we can merge it. We still need to update the matrix_RE.txt  for GPU wfs.

FYI @silviodonato , @qliphy , @fwyzard

**Comment by slava77** [comment]
> If this looks good then we can merge it. We still need to update the matrix_RE.txt for GPU wfs.

This looks good indeed.
I will update the matrix_RE.txt  some time later today.

Thank you.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
