### PR TITLE
[hlt-p2-int] Control the parallel running processes

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- enable = hlt_p2_integration

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@mmusich , hlt-p2-integration PR job ran successfully ( https://cmssdt.cern.ch/jenkins/job/ib-run-pr-hlt_p2_integration/3/console ). Looks like `hltDiff` [part](https://github.com/cms-sw/cmssw/blob/master/HLTrigger/Configuration/scripts/hltPhase2UpgradeIntegrationTests#L300-L335) runs in serial mode and took most of the job time ( 13mins out of 24mins). I think `compare_hlt_results` found can also run `hltDiff` in parallel ... right?

**Comment by mmusich** [comment]
>  I think compare_hlt_results found can also run hltDiff in parallel ... right?

Indeed, can work on that tomorrow.

**Pull request merged**
