### PR TITLE
add HCALOnly wf to MATRIX_EXTRAS_GPU

### PR DESCRIPTION
**Pull request by slava77**
it looks like we are not testing the HCAL GPU workflow.

@fwyzard  was it intentional (that .522 is broken/unstable) or a result of minimization of the number of workflows?

### CODE REVIEW

**Comment by fwyzard** [comment]
Not intentional, I guess it simply for lost ?

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by slava77** [comment]
@smuzaffar @mrodozov 
is there a way to make baseline IB outputs for MATRIX_EXTRAS_GPU?

**Comment by smuzaffar** [comment]
@slava77 , no currently there is no option

**Comment by slava77** [comment]
> @slava77 , no currently there is no option

it would be nice to get it added some time soon.
Well, by "it" I include also a case when these (now 3) workflows run for every IB.
Some more optimal variant could be to trigger the baseline when missing for cases when there is a PR which has "enable gpu" as a part of "please test", but could also be a manually "please check baseline" based on the PR test parameters so that we can have a "N-1" baseline possibility as well.

For now, I think that this PR is OK considering that all 3 workflows completed.

**Comment by smuzaffar** [comment]
@slava77 , #1521 should enable GPU comparisons

**Pull request merged**
