### PR TITLE
Mount /var/run/user and /run/user

### PR DESCRIPTION
**Pull request by iarspider**
needed for gpg agent's socket

### CODE REVIEW

**Comment by iarspider** [comment]
Testing here: https://cmssdt.cern.ch/jenkins/job/cms-spack-build-singularity/55/

**Comment by smuzaffar** [comment]
please test

lets test if this works for normal PR jobs

**Comment by smuzaffar** [comment]
please test for CMSSW_5_3_X

**Comment by smuzaffar** [comment]
please test for CMSSW_12_3_X

**Comment by smuzaffar** [comment]
@iarspider , did this work for spack?

**Comment by iarspider** [comment]
@smuzaffar yes.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
