### PR TITLE
reco comparisons: cleanup/simplify mapping patterns for shorthand workflow maps

### PR DESCRIPTION
**Pull request by slava77**
- mostly technical pattern simplification: simplify dir matching patterns with currently necessary map disambiguation
- style fix for shorthand naming of 10805 nano workflow
- also, a bugfix in map for 20411.0 (wrong mapping)

to support updates made in cms-sw/cmssw#30988
the update map should still work on past releases

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test with cms-sw/cmssw#30988

**Comment by slava77** [comment]
@cmsbuild please test

to check the default

**Comment by smuzaffar** [comment]
@slava77 , are these changes compatible with other release cycles e.g 5.3.X to 11.1.X?

**Comment by slava77** [comment]
> @slava77 , are these changes compatible with other release cycles e.g 5.3.X to 11.1.X?

they should be, in this PR I made more inclusive patterns, I did not remove any old mappings.

The current comparison job should cover 11_1_X part of the question, just to be sure.

53X does not have workflows in the range modified in this PR.

**Comment by silviodonato** [comment]
please test for CMSSW_10_2_X

**Comment by silviodonato** [comment]
merge
(needed for https://github.com/cms-sw/cmssw/pull/30988)

**Pull request merged**
