### PR TITLE
Update workflows to monitor in PR profiling

### PR DESCRIPTION
**Pull request by jfernan2**
Changed to monitor wf 29834.21 (D110 upgrade) and 12634.21 (Run3 2023)

### CODE REVIEW

**Comment by srimanob** [comment]
Hi @jfernan2 
Should you use 29834.21 instead? It is PU workflow.

**Comment by jfernan2** [comment]
Correct @srimanob  I have fixed it
Thanks!

**Comment by smuzaffar** [comment]
enable profiling

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@jfernan2 , looks like `12634.21` is not a valid workflow (at least it is not in 14.1.X) or do we need to pass any extra option to `runTheMatrix.py` to run it?

**Comment by srimanob** [comment]
> @jfernan2 , looks like `12634.21` is not a valid workflow (at least it is not in 14.1.X) or do we need to pass any extra option to `runTheMatrix.py` to run it?

Hi @smuzaffar 
It will need `relvals_opt = --what upgrade` as the workflow has not defined in https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_2017.py yet.

**Comment by srimanob** [comment]
I create the following PR since the workflow should be defined in relval_2017,
https://github.com/cms-sw/cmssw/pull/45381

**Comment by smuzaffar** [comment]
So we need to provide a way to instruct bot how to run workflows which are not active by default for runTheMatrix. We can add a variable e.g `PROFILING_OPTS="-w upgrade,standard"`  in https://github.com/cms-sw/cms-bot/blob/master/cmssw-pr-test-config so that bot can use it when running runTheMatrix

**Comment by srimanob** [comment]
> So we need to provide a way to instruct bot how to run workflows which are not active by default for runTheMatrix. We can add a variable e.g `PROFILING_OPTS="-w upgrade,standard"` in https://github.com/cms-sw/cms-bot/blob/master/cmssw-pr-test-config so that bot can use it when running runTheMatrix

That would be useful so that we can handle upgrade workflow. Thanks @smuzaffar 
Since the workflows we need should be in relval_2017 anyways, so maybe we can merge https://github.com/cms-sw/cmssw/pull/45381 (after PR tests) then follows by this PR.

**Comment by jfernan2** [comment]
dear @srimanob aqnd @smuzaffar 
Now that https://github.com/cms-sw/cmssw/pull/45381  has been merged, could we revive this PR? Thanks

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
looks good

**Comment by jfernan2** [comment]
@smuzaffar after the inclusion of this PR, I thought we could have profiling comparison in PR tests, but it looks like something else is missing, see for example last trial:
https://github.com/cms-sw/cmssw/pull/45333
Profiling results for 12634.21 and 29834.21 are there but comparison is empty:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d1a85e/40514/summary.html
I fail to see the reason why since the logs shows all OK, apparently:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d1a85e/40514/testsResults/profiling.txt
Do you have any hint?
Thanks

**Comment by smuzaffar** [comment]
@jfernan2 , though PR and baseline jobs were run for these workflows but I think we need `DQM*.root` files for comparison and these works [12634.21](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d1a85e/40514/runTheMatrix-results/12634.21_TTbar_14TeV+2023PU_ProdLike/) and [29834.21](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d1a85e/40514/runTheMatrix-results/29834.21_TTbar_14TeV+2026D110PU_ProdLike/) do not generate such output that is why comparison was not run

**Comment by jfernan2** [comment]
No, I was referring to the igprof text results comparison, these comparison files are empty:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d1a85e/40514/profiling/12634.21/RES_CPU_compare_12634.21.txt
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d1a85e/40514/profiling/29834.21/RES_CPU_compare_29834.21.txt
Thanks

**Comment by smuzaffar** [comment]
may be  @gartung  knows why profiling comparison is empty

**Comment by makortel** [comment]
> may be @gartung knows why profiling comparison is empty

@gartung is on vacation until August 9.

**Comment by gartung** [comment]
It looks like a segfault in the deco step got 12634.21
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d1a85e/40514/profiling/12634.21/step3_igprof_cpu.log

**Comment by gartung** [comment]
Segfault in the record step for 29834.21 as well
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d1a85e/40514/profiling/29834.21/step3_igprof_cpu.log

**Comment by jfernan2** [comment]
Thanks @gartung 
I am trying a last time since it worked in https://github.com/cms-sw/cms-bot/issues/1912

**Comment by jfernan2** [comment]
@gartung   the same two workflows 29834.21 and 12634.21 run fine with igprof in Jenkins profiling[1]

I believe the difference is on how igprof is called with -j JobReport

igprof -pp -d -t cmsRun -z -o ./igprofCPU_step3.gz -- cmsRun step3_igprof.py -j step3_igprof_cpu_JobReport.xml >& step3_igprof_cpu.log   -> crashes

igprof -d -pp -z -o step3_igprofCPU.gz -t cmsRun cmsRun step3_igprof.py     -> runs fine

Somehow it was removed for igprof here[2], so I am proposing the following PR if you agree: 

https://github.com/cms-cmpwg/profiling/pull/8

[1] https://cmssdt.cern.ch/jenkins/job/release-run-reco-profiling/533/console
https://cmssdt.cern.ch/jenkins/job/release-run-reco-profiling/538/console
[2] https://github.com/cms-sw/cms-bot/blob/5bac572863f680e3d69e22005e437665b5df666f/reco_profiling/profileRunner.py#L335

**Comment by makortel** [comment]
> I believe the difference is on how igprof is called with -j JobReport

I'd find it very strange if the framework job report would be causing segfaults under IgProf, but who knows.

**Comment by jfernan2** [comment]
Me too @makortel but I have just repeated the test in Jenkins with success for both workflows using igprof and no JobReport output....

**Comment by jfernan2** [comment]
@smuzaffar   igprof is still giving problems, however the baseline seems to not be running igprof for the two wfs in question (12634.21 and 29834.21), so we miss the reference anyway, see fopr example this recent trial:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_14_2_X_2024-09-01-2300/el8_amd64_gcc12/-GenuineIntel/matrix-results/

Any idea? Thanks

**Pull request merged**
