### PR TITLE
added --maxmem_profile for default production arch relvals

### PR DESCRIPTION
**Pull request by smuzaffar**
This PR enables the `--maxmem_profile` flag (if available) for production arch relval tests. Flag will be added only to default workflows (plus any extra workflows enabled via `please test workflow wf-num`) for production arch. Any special flavors (e.g. nano, high-stats, gpu or non-product IBs/archs) will not enable this.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@makortel @gartung , look like `--maxmem_profile` option for `cmsDriver.py` and not for `runTheMatrix.py`. Also looks like it [does not work](https://github.com/cms-sw/cmssw/blob/master/Configuration/Applications/python/cmsDriverOptions.py#L253-L256) if `--prefix` option is passed to `cmsDriver`.  We do use `--prefix` e.g. to pass `timeout --signal SIGTERM 9000` to kill jobs which hangs or to monitor the resource utilization of workflow step

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
yes @makortel , we should update bot to ignore memory profile output line. If would be easier if either
```
Memory Report
  total memory requested: 536
  max memory used: 536
  presently used: 24
  # allocations calls:   7
  # deallocations calls: 8
```
is written in one line i.e. `Memory Report: total memory requested: 536, max memory used: 536. ...` or each line is prefixed by something e.g.
```
Memory Report:  total memory requested: 536
Memory Report:  max memory used: 536
Memory Report:  presently used: 24
Memory Report:  # allocations calls:   7
Memory Report:  # deallocations calls: 8
```

**Comment by makortel** [comment]
@Dr15Jones Could you update (or comment) the `MaxMemoryPreload` along https://github.com/cms-sw/cms-bot/pull/2202#issuecomment-2011363615 ? Maybe e.g. `MaxMemoryPreload:` prefix would make it clear where the printout comes from?

**Comment by Dr15Jones** [comment]
> Maybe e.g. MaxMemoryPreload: prefix would make it clear where the printout comes from?

See https://github.com/cms-sw/cmssw/pull/44502

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#44502

**Comment by smuzaffar** [comment]
Thanks @Dr15Jones for https://github.com/cms-sw/cmssw/pull/44502, bot now can ignore following lines from the workflow logs
```
Memory Report: total memory requested: 536
Memory Report:  max memory used: 536
Memory Report:  presently used: 24
Memory Report:  # allocations calls:   7
Memory Report:  # deallocations calls: 8
```

I think we can merge this PR on Monday morning.

**Comment by makortel** [comment]
Thanks!

**Comment by smuzaffar** [comment]
@makortel , this has been merged and starting from today's IB `CMSSW_14_1_X_2024-03-25-1100` both baseline and PR relvals contains the max memory profile information

**Comment by makortel** [comment]
Thanks!

**Pull request merged**
