### PR TITLE
reco comparisons: add a minimal set of wf maps for D77

### PR DESCRIPTION
**Pull request by slava77**
this will catch up with changes in cms-sw/cmssw#35862

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test with cms-sw/cmssw#35862,cms-sw/cmssw#35766

**Comment by srimanob** [comment]
Thanks @slava77

**Comment by smuzaffar** [comment]
@cmsbuild please test with cms-sw/cmssw#35862,cms-sw/cmssw#35766

**Comment by slava77** [comment]
it would be nice to get this in, before the tests start picking up CMSSW_12_2_X_2021-11-01-1100

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
