### PR TITLE
Add ml-prod to groups.yaml.

### PR DESCRIPTION
**Pull request by riga**
Hi!

I hope I added this at the right spot.
Of course, feel free to rename in case there is a common pattern that I missed.

@yongbinfeng

### CODE REVIEW

**Comment by smuzaffar** [comment]
@riga , if this group is needed to watch changes (get github notifications) when a change is requested for some selected packages then yes this is right place but you also need to update either `category-watchers.yaml` (if you want to watch all packages changes belonging to a [category](https://github.com/cms-sw/cms-bot/blob/master/categories_map.py)) or `watchers.yaml` (if you want to watch only a selected packages).

**Comment by riga** [comment]
I think we would continue to configure watched packages on a per-user basis, but I'll check that again and maybe create a second PR in the future.

Just to be sure, the entry in groups.yaml allows people to contact us by including `@ml-prod`, right?

**Comment by smuzaffar** [comment]
> Just to be sure, the entry in groups.yaml allows people to contact us by including @ml-prod, right?

No, this is not true. Note that `ml-prod` could be a valid github user and by doing `@ml-prod` you basically notify that person :-)

**Comment by riga** [comment]
Ok, I had that suspicion already ... then we'll get in touch with other groups on best practices for that. Thank you!

Feel free to close :-)

**Comment by makortel** [comment]
How about `@cms-sw/ml-l2` team?

**Pull request closed without merging**
