### PR TITLE
unset SINGULARITY_BIND inside singularity

### PR DESCRIPTION
**Pull request by smuzaffar**
as reported here https://github.com/cms-sw/cmssw/issues/32918

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = HeterogeneousCore/SonicTriton

**Comment by smuzaffar** [comment]
please test

**Comment by kpedro88** [comment]
@smuzaffar maybe it's worth copying the value of this variable into another variable that won't be recognized by Singularity, so that users can still check what was bound after activating the container?

**Comment by kpedro88** [comment]
@smuzaffar actually, since this only affects the bot, maybe it doesn't matter. But we might want to consider whether this should be a default feature in https://github.com/cms-sw/cmssw-osenv/blob/master/cmssw-env

**Comment by smuzaffar** [comment]
ah I notcied that instead singularity the variable is `SINGULARITY_BIND` while singularity uses `SINGULARITY_BINDPATH` for binding , so may be this is not needed

**Comment by smuzaffar** [comment]
singularity docs  ( https://sylabs.io/guides/3.0/user-guide/bind_paths_and_mounts.html ) says that it uses both `SINGILARITY_BIND` and `SINGILARITY_BINDPATH`

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Pull request merged**
