### PR TITLE
Add new GT package category mapping for L1 and upgrade

### PR DESCRIPTION
**Pull request by aloeliger**
This PR creates a category mapping for the new GT emulator package proposed by the L1T Phase 2 Global Trigger Emulator team in https://github.com/cms-sw/cmssw/pull/41808. This PR should map the new package missing in buildbot to require L1 and upgrade signatures.

### CODE REVIEW

**Comment by smuzaffar** [comment]
assign upgrade

any objections @cms-sw/upgrade-l2 ?

**Comment by srimanob** [comment]
assign l1

**Comment by srimanob** [comment]
Thanks @smuzaffar 
We will follow up.

**Comment by aloeliger** [comment]
@smuzaffar This is my first time having to map new packages for buildbot. Is the `new-package-pending` label blocking? Does this need to be merged first, or does the PR need to pull this in as an external to remove that label or something like that?

**Comment by aloeliger** [comment]
@aandvalenzuela Doesn't matter to me as long as they both end up in there at some point. This was opened because buildbot asked for a PR on the new package. I don't expect anything will go into the new package before the GT team gets the initial emulator commit in there.

**Comment by smuzaffar** [comment]
@aandvalenzuela bot changes should be merged first so that bot can properly assign categories for cmssw pr. For this chamge we need @cms-sw/upgrade-l2 to agree first. Once upgrade is happy with thus update then you can merge it

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
@smuzaffar 
Thanks for pinging. Please merge.

**Comment by aloeliger** [comment]
+l1

if it helps

**Comment by perrotta** [comment]
merge

**Pull request merged**
