### PR TITLE
Changes in DQM responsibles

### PR DESCRIPTION
**Pull request by jfernan2**
Removing people not working in DQM any longer
Adding new convener Emanuele Usai and two new DQM operators: Petr Mandrik and Peerut Boonchokchuay

### CODE REVIEW

**Comment by mrodozov** [comment]
@pmandrik @pbo0 @perrotta

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
Sorry, I did not want to trigger any test for this
I have no objections, as I think that @jfernan2 knows well who has responsabilities for the DQM code.

**Comment by jfernan2** [comment]
Indeed, the changes have been agreed in today's DQM core meeting, and all parts involved are in agreement.
Thanks

**Pull request merged**
