### PR TITLE
reco comparisons: TICL monitoring: tracksters with multiclusters, TICL and PF Candidates

### PR DESCRIPTION
**Pull request by slava77**
updates in validate.C used for reco comparisons. The main part is the addition of monitoring for TICL reconstruction, which is available in the default workflows since 11_1_0_pre6.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
it may be better to merge this only after cms-sw/cmssw#29616 is merged to avoid random differences in comparisons

**Comment by slava77** [comment]
@cmsbuild please test

after CMSSW_11_1_X_2020-05-04-2300 the differences in reco should go away

**Comment by smuzaffar** [comment]
@slava77 , is ready to go in now?

**Comment by slava77** [comment]
> @slava77 , is ready to go in now?

yes, it's ready.
Thanks for checking.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
