### PR TITLE
reco comparisons updates: new map, chi2 variables for HI

### PR DESCRIPTION
**Pull request by slava77**
- D60 workflows are added to the map; this is needed starting CMSSW_11_2_X_2020-07-14-2300 for proper running of reco comparisons in the standard jenkins tests 
- chi2 variables are added, in connection with cms-sw/cmssw#30566

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild 
please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
>     * the warning as e.g. in [cms-sw/cmssw#30697 (comment)](https://github.com/cms-sw/cmssw/pull/30697#issuecomment-658936235)
>       is gone
> 
>     * logs show that the trackChi2 plot compiled OK (there was nothing to plot though in the out-of-the box case)

so, I think that this is ready to merge.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
