### PR TITLE
add 136.889 to pr profiling  wf list

### PR DESCRIPTION
**Pull request by slava77**
this is in a follow up to https://github.com/cms-sw/cms-bot/pull/1712#issuecomment-1043295212

### CODE REVIEW

**Comment by slava77** [comment]
enable profiling

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by gartung** [comment]
I need to add a check for workflow number and use the right category.

**Comment by smuzaffar** [comment]
I would suggest to use `runTheMatrix.py -n | grep "^$wf "`  as this will avoid hardcoded workflow numbers in `cms-cmpwg/profiling` and should work for future updates of workflows in cms-bot

**Comment by gartung** [comment]
I changed it to use your suggestion and tested that it does what I expect.
```
(runTheMatrix.py -n | grep -^$PROFILING_WORKFLOW " 2>/dev/null) || WHAT='-w upgrade'
runTheMatrix.py $WHAT -l $PROFILING_WORKFLOW --ibeos --command=--number=$EVENTS\ --nThreads=$NTHREADS\ --no_exec #200PU for 11_2_X
```

**Comment by smuzaffar** [comment]
> I changed it to use your suggestion and tested that it does what I expect.
> 
> ```
> (runTheMatrix.py -n | grep "^$PROFILING_WORKFLOW " 2>/dev/null) || WHAT='-w upgrade'
> runTheMatrix.py $WHAT -l $PROFILING_WORKFLOW --ibeos --command=--number=$EVENTS\ --nThreads=$NTHREADS\ --no_exec #200PU for 11_2_X
> ```

looks good, let me restart the iprofiling job now

**Comment by slava77** [comment]
the profiling results display for 136.889 may need an improvement in formatting:
image

A `<br>` would be useful to get an offset.

Perhaps more importantly, the workflow itself did not really work
based on the logs in [PR-d982d3/22509/profiling/136.889](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d982d3/22509/profiling/136.889/)


[step3_igprof_cpu.log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d982d3/22509/profiling/136.889/step3_igprof_cpu.log) is apparently a result of running step4_HARVESTING.py (based on the error message), while it should be running `step3*.py`

The `step4_igprof_cpu.log` seems to be for something that didn't even parse to a `py` config file.


https://cmssdt.cern.ch/jenkins/job/ib-run-pr-profiling/205/consoleFull
is suggestive that there is some mismatch in the stepN file generation:
- ```echo ' cmsDriver.py step3  --conditions auto:run2_data ... --python_filename=step2_timememoryinfo.py``` was supposed to map to `step3*py` (the job actually ran, based on the available log)
- there is also an attempt to make step5, which does not exist for this workflow

**Comment by gartung** [comment]
[This fixes the PR report formatting.](https://github.com/cms-sw/cms-bot/pull/1715)
Profiling scripts have bee updated to deal with reHLT workflow.

**Comment by slava77** [comment]
> [This fixes the PR report formatting.](https://github.com/cms-sw/cms-bot/pull/1715) Profiling scripts have been updated to deal with reHLT workflow.

Thank you for the updates.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by gartung** [comment]
The [circles graph](https://cmssdt.cern.ch/circles/web/piechart.php?local=false&dataset=CMSSW_12_3_X_2022-02-21-1100%2Fslc7_amd64_gcc10%2F136.889%2FPR-e618a8%2F22562%2Fstep3_RAW2DIGI_L1Reco_RECO_SKIM_PAT_ALCA_DQM.resources&resource=time_thread&colours=default&groups=packages&threshold=0) for #1715

**Comment by slava77** [comment]
> The [circles graph](https://cmssdt.cern.ch/circles/web/piechart.php?local=false&dataset=CMSSW_12_3_X_2022-02-21-1100%2Fslc7_amd64_gcc10%2F136.889%2FPR-e618a8%2F22562%2Fstep3_RAW2DIGI_L1Reco_RECO_SKIM_PAT_ALCA_DQM.resources&resource=time_thread&colours=default&groups=packages&threshold=0) for #1715

This looks as expected (matches the workflow and the auto-formatted categories are OK). Nice.

**Pull request merged**
