### PR TITLE
Run cudaComputeCapabilities in addition to nvidia-smi

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please abort

**Comment by smuzaffar** [comment]
test parameters:
- enable = gpu

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

```
> cudaComputeCapabilities
   0     8.0    NVIDIA A100-PCIE-40GB
```

**Pull request merged**
