### PR TITLE
Updated profiling result checked for to Run3 workflow 11834.21

### PR DESCRIPTION
**Pull request by gartung**
This will enable Resource Piecharts and Reco Event loop links that have been missing since the update to the HLLHC workflow 39634.21.

### CODE REVIEW

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
@aandvalenzuela  @iarspider can you please merge this after the tests complete

**Comment by aandvalenzuela** [comment]
Sure @gartung, I will keep an eye on. Thank you!

**Comment by aandvalenzuela** [comment]
+1

**Pull request merged**
