### PR TITLE
run trigger comparison in parallel with JR to save some time

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
@missirol , @fwyzard this should improve the parallelism by running the TR jobs along with JR jobs. I will use this PR to test old release cycles too

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_11_2_X

**Comment by smuzaffar** [comment]
please test for CMSSW_5_3_X

**Comment by missirol** [comment]
For the previous comparisons, the output looks okay (although the summary message is not shown; maybe that is by design?):
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_3_X_2021-03-15-2300+124374/41720/triggerResults/

For `5_3_X`, the TriggerResults comparisons failed because `argparse` could not be loaded:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_5_3_X_2021-03-14-0000+124374/41724/triggerResults.log

**Comment by smuzaffar** [comment]
+externals
I think bot got confused by CMSSW_11_2_X and CMSSW_11_3_X tests that is why the https://github.com/cms-sw/cms-bot/pull/1508#issuecomment-800206028 is not complete. 
So looks like new tests is safe and will not break the comparison job. We might only miss the edm::TriggerResults for old releases

**Pull request merged**
