### PR TITLE
Keep backup copy of static analyzer index. Log postprocessing to log.

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
@mrodozov This needs to be merged so I can figure out how moving to python3 messed up postprocess-scan-build.py

**Comment by silviodonato** [comment]
@gartung @sroychow noticed that the static analyzer does not work anymore
https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_11_3_X_2021-05-27-2300/slc7_amd64_gcc900/llvm-analysis/index.html


in https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_12_0_X_2021-05-27-2300/slc7_amd64_gcc900/reports/eventsetuprecord-get.txt I see
```
File "./callgraph.py", line 36
    fields = line.split("'")
                           ^
TabError: inconsistent use of tabs and spaces in indentation
```

The issue appeared with `CMSSW_12_0_X_2021-05-24-2300` 
see 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_12_0_X_2021-05-24-2300/slc7_amd64_gcc900/reports/
vs
https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_12_0_X_2021-05-24-1100/slc7_amd64_gcc900/reports/

**Comment by gartung** [comment]
Also https://github.com/cms-sw/cms-bot/pull/1558

**Pull request merged**
