### PR TITLE
Unit tests for process_pr script

### PR DESCRIPTION
**Pull request by iarspider**
test parameters:
- skip_test = static,header

### CODE REVIEW

**Comment by smuzaffar** [comment]
ping bot

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_5_3_X

**Comment by smuzaffar** [comment]
test parameters:
- skip_test = static,header

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_5_3_X

**Comment by smuzaffar** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_5_3_X

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test for CMSSW_5_3_X

**Comment by smuzaffar** [comment]
+externals

looks good

**Pull request merged**
