### PR TITLE
Resources comparison: Compare absolute difference of fraction of total time per module

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
@smuzaffar is there any way to skip the Black formatting check other than fixing files not related to my change?

**Comment by gartung** [comment]
enable profiling

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
It's not a blocking test anymore. I was able to start testing.

**Comment by smuzaffar** [comment]
yes, formatting test does not block the normal PR tests

**Comment by gartung** [comment]
please test

**Comment by jfernan2** [comment]
Any progress in this front? I cannot see the difference any longer, I guess it was removed from the web since it is 5 day old already, is this expected?

**Comment by gartung** [comment]
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4248f1/42866/profiling/29834.21/diff-step3_cpu.resources.json.html
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4248f1/42866/profiling/12634.21/diff-step3_cpu.resources.json.html

**Comment by gartung** [comment]
The thresholds are 5% and 20% now. I am working on sorting by thread fraction differences.

**Comment by jfernan2** [comment]
OK, it looks better to me, I was looking to links dubbed [diff-CMSSW_14_2_X_2024-11-14-1100-step2_cpu.resources.json] which are broken in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4248f1/42866/profiling/index-29834.21.html

**Comment by gartung** [comment]
They are not broken. Step 2 is not run because of mixing. Are you interested in the HLT modules too?

**Comment by gartung** [comment]
please test

**Comment by jfernan2** [comment]
> They are not broken. Step 2 is not run because of mixing. Are you interested in the HLT modules too?

No, sorry, as RECO convener I am interested in step3, which is apparently broken:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4248f1/42866/profiling/29834.21/diff-CMSSW_14_2_X_2024-11-14-1100-step3_cpu.resources.json.html
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4248f1/42866/profiling/12634.21/diff-CMSSW_14_2_X_2024-11-14-1100-step3_cpu.resources.json.html

but I am not sure if these are the old links, which perhaps should be rmeoved, or if there is any difference with the new ones you have set

**Comment by gartung** [comment]
Oh! Sorry the diff-CMSSW*.json files are produced because the script loops over all json files and I copy in the json files from the IB to that name.

**Comment by gartung** [comment]
abort

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
abort

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@gartung , is this ready ?

**Comment by gartung** [comment]
yes

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
