### PR TITLE
added helper scirpt to build and test cms prs

### PR DESCRIPTION
**Pull request by smuzaffar**
A helper scipt added to easily build and test cms PRs. This include cmdist, cms-externals and cms-data.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
@smuzaffar for my understanding, what is the idea behind this script? How is this supposed to be used vs the standard bot machinery?

**Comment by smuzaffar** [comment]
@fabiocos , this is standalone script which one can use locally to build cms externals. Mostly it is for those users who asked us how to build locally an external or cmsdist PR and test it in cmssw env. Now one should be able to run `./test_prs.sh cms-sw/cmsdist#PR1 cms-sw/cmssw#PR2` which should 
- build full cmssw-tool-conf
- create a cmssw dev area based on latest IB
- setup new cmssw-tool-conf in cmssw dev area
- checkout packages which require re-build due to changed externals
- checkout and extra cmssw PRs
- run scram build
it will not run any tests. Idea is to just setup the cmssw env with changed externals so that one can reproduce/fix the errors

**Comment by fabiocos** [comment]
@smuzaffar thank you, I see it is complementary to the basic procedure https://twiki.cern.ch/twiki/bin/view/CMS/SDTExternalsWithCMSSW in the sense that one can just test directly a CMSDIST PR. I'll give it a try

**Pull request merged**
