### PR TITLE
Replace L1 secondary signature.

### PR DESCRIPTION
**Pull request by rekovic**
Replace L1 signature from Ben Krikler to Javier Duarte, who will be helping with signatures.

### CODE REVIEW

**Comment by smuzaffar** [comment]
any objections @benkrikler and @jmduarte

**Comment by silviodonato** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
@smuzaffar
Please merge so that Javier Duarte can start helping with L1 signatures.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
