### PR TITLE
Update value of profiling wf 39634.21 to 21034.21

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Resolves https://github.com/cms-sw/cms-bot/issues/1854

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
test parameters:
- enable_test = profiling

**Comment by aandvalenzuela** [comment]
please test

**Comment by smuzaffar** [comment]
@aandvalenzuela , note that https://github.com/cms-sw/cms-bot/blob/master/cmssw-pr-test-config is used by all release cycles, so if new workflow is not part of 12.4.X/12.5.X releases then igprof job will start failing for those release cycles

**Comment by gartung** [comment]
https://github.com/cms-sw/cms-bot/pull/1861

**Comment by smuzaffar** [comment]
lets  run for both workflows and @gartung change https://github.com/cms-sw/cms-bot/pull/1861 should properly ignore the missing workflow

**Comment by smuzaffar** [comment]
please test

**Pull request merged**
