### PR TITLE
Add code to support triggering GPU unit-tests from bot

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
I have added the flag to [ib-run-pr-tests](https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/) job, copied it and the logic to choose node from relvals one

**Comment by smuzaffar** [comment]
@iarspider  , please revert the change for [ib-run-pr-tests](https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/) job. We do not want to change that job otherwise we will not run non-GPU unit test. We want to run an extra job (which should be identical to https://cmssdt.cern.ch/jenkins/job/ib-run-pr-addon/ but sould run unit tests for gpu

**Comment by smuzaffar** [comment]
-externals

**Comment by smuzaffar** [comment]
we should add a new script `run-pr-unittests.sh` same as https://github.com/cms-sw/cms-bot/blob/master/pr_testing/run-pr-addon.sh but instead of running addon tests it should run `scram build unittests`

**Pull request closed without merging**
