### PR TITLE
Reformat all python script with Black

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#8791

**Comment by smuzaffar** [comment]
please test for CMSSW_8_0_X

**Comment by iarspider** [comment]
Notice: I propose to make the resulting commit authored by cms-bot. There is also a way to make github (automatically) and git client (semi-automatically, unfortunately) to ignore the formatting commit - see, e.g., [this article](https://moxio.com/blog/ignoring-bulk-change-commits-with-git-blame/). I would also propose to rename all python files to end with `.py`, and make original names symlinks (or dummy shell scripts running `python3 <myname>.py`). This will help to avoid explicitly listing all additional python scripts that need to be checked at push.

**Comment by iarspider** [comment]
> I found 25 errors in the following unit tests:

Also present [in IBs](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc6_amd64_gcc530/www/sun/8.0-sun-00/CMSSW_8_0_X_2023-10-29-0000?utests)

**Comment by smuzaffar** [comment]
thanks @iarspider , changes looks good.  Can we run `black` during the github actions?

>     1. I propose to make the resulting commit authored by cms-bot.

there is no need for cms-bot/build to be the author.

>     2. There is also a way to make github (automatically) and git client (semi-automatically, unfortunately) to ignore the formatting commit - see, e.g., [this article](https://moxio.com/blog/ignoring-bulk-change-commits-with-git-blame/).

If I am reading the above artica correctly then looks like git client (version >=2.32) can ignore a commits for blame but github and gitlab do not support it yet. 

If you want then please go ahead and add `.git-blame-ignore-revs` file too
 
>     3. I also propose to rename all python files to end with `.py`, and make original names symlinks (or dummy shell scripts running `python3 <myname>.py`). This will help to avoid explicitly listing all additional python scripts that need to be checked at push.

sounds good. May be you can do this once this PR is merged.

**Comment by iarspider** [comment]
https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

**Comment by iarspider** [comment]
Let's merge https://github.com/cms-sw/cms-bot/pull/2096, I will then rebase this one on top so that I don't have to reformat files touched in that one again.

**Comment by smuzaffar** [comment]
looks good, lets get this in

**Pull request merged**
