### PR TITLE
Run scram build commands under /usr/bin/time

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = FWCore

**Comment by smuzaffar** [comment]
@makortel , this runs `scram build` under `/usr/bin/time` see logs https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-854405/42991/build.log . Should I add a should message in PR summary comment about the compilation time ?

**Comment by makortel** [comment]
Is it this printout?
```
	Command being timed: "scram b -v -k -j 16"
	User time (seconds): 2174.57
	System time (seconds): 435.37
	Percent of CPU this job got: 1365%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 3:11.17
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 998052
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 10255
	Minor (reclaiming a frame) page faults: 79924363
	Voluntary context switches: 2068017
	Involuntary context switches: 3297393
	Swaps: 0
	File system inputs: 0
	File system outputs: 2887392
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```
This printout is much more extensive than what I've usually seen with `/usr/bin/time` :)

> Should I add a should message in PR summary comment about the compilation time ?

I'm not sure. My feeling is that it is not generally useful for the PR review itself, but could be informative. So I don't think it is really necessary (at this point), but I'm not against of including it.

**Comment by smuzaffar** [comment]
> Is it this printout?

yes, this is with `/usr/bin/time -v`

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
