### PR TITLE
Addition of timing and memory check if available in PR matrix test

### PR DESCRIPTION
**Pull request by fabiocos**
Cleaned version of #1122 with protection for non existent customisation file (for old branches)

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

this should verify that nothing is broken in case the fragment is not merged

**Comment by fabiocos** [comment]
@smuzaffar ok, the added protection seems to work

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
looks good.

**Pull request merged**
