### PR TITLE
support for adding new type labels

### PR DESCRIPTION
**Pull request by smuzaffar**
This allows bot to add new type labels e.g. `type name1(,name2|)` . Existing type labels were `bug-fix` and `new-feature`. This PR also added 
- `documentation`
- `performance-improvements`
- `new-idea` : but may be we do not need this in favor of existing `new-feature`

FYI @qliphy  @perrotta

### CODE REVIEW

**Comment by smuzaffar** [comment]
@qliphy @perrotta the newly added colors can be seen here https://github.com/smuzaffar/SCRAM/pull/5

**Comment by qliphy** [comment]
@smuzaffar   thanks a lot!  +1 from here.

**Comment by perrotta** [comment]
Thank you Shahzad!
That's fine also to me: +1

**Comment by smuzaffar** [comment]
ok thanks, I have updated http://cms-sw.github.io/cms-bot-cmssw-cmds.html to include the informaton about new labels/type comments. With in 30 mins new labels will be available for all of repositories

**Pull request merged**
