### PR TITLE
add L1THGCal packages, and watchers

### PR DESCRIPTION
**Pull request by lgray**
For https://github.com/cms-sw/cmssw/pull/13156. 
Please merge this soon! Thanks!

### CODE REVIEW

**Comment by degano** [comment]
@davidlange6 @slava77 Any objection on creating a new subpackage?

**Comment by slava77** [comment]
@mulhearn
this will end up on your list
If there are any concerns about naming style better clear it now

**Comment by mulhearn** [comment]
sure my tenure as L2 will hopefully be over by then anyway ;-)

**Comment by lgray** [comment]
@slava77 I guess that's a yes. Please move this forward. Thank you!

**Pull request merged**
