### PR TITLE
add CalibTracker/SiStripHitResolution package to alca category

### PR DESCRIPTION
**Pull request by mmusich**
Title says it all, needed by https://github.com/cms-sw/cmssw/pull/40754

### CODE REVIEW

**Comment by mmusich** [comment]
can this be considered for merge? (even though I didn't receive comments on https://github.com/cms-sw/cmssw/pull/40754 yet)

**Comment by aandvalenzuela** [comment]
Hello @mmusich, I was waiting for https://github.com/cms-sw/cmssw/pull/40754 to be ready, but I can merge already this one (no testing is needed in `categories_map` and only a module is added). Let me know if you prefer to wait or to merge it now

**Comment by mmusich** [comment]
> I was waiting for https://github.com/cms-sw/cmssw/pull/40754 to be ready, but I can merge already this one

Hi @aandvalenzuela, provided @cms-sw/alca-l2 agree with the addition of a new package, I think we can go ahead and merge this one.

**Comment by francescobrivio** [comment]
+1 from @cms-sw/alca-l2

**Pull request merged**
