### PR TITLE
Update GPU RelVals to 2024 wfs

### PR DESCRIPTION
**Pull request by AdrianoDee**
This PR proposes to update the GPU RelVals to 2024 wfs for CMSSW >= 14 and add the TTBar pixel triplets wf. Marking it a draft waiting for https://github.com/cms-sw/cmssw/pull/45694.

### CODE REVIEW

**Comment by smuzaffar** [comment]
enable gpu

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_14_0_X

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

@AdrianoDee , this looks good, is it ready to go in now?

**Comment by AdrianoDee** [comment]
Yes @smuzaffar, thanks!

**Pull request merged**
