### PR TITLE
Temporarily move the production architecture for 8_0_X and 9_4_X to slc7

### PR DESCRIPTION
**Pull request by fabiocos**
It has been agreed with PPD/PdmV and O&C to have dedicated 8_0_X and 9_4_X builds for the Ultra-Legacy HLT on MC where the production architecture is moved from slc6 to slc7 to allow a seamless step-chain processing. This will be reverted after the builds, so as not to modify possible further updates for ongoing production not related to UL builds.

### CODE REVIEW

**Comment by fabiocos** [comment]
@mrodozov this is what we have discussed, my plan is:

- merge it now;
- make the two builds that need the swap;
- revert it tomorrow.

Do you see any drawbacks? It should not interfere with regular operations, as we are not making 8_0_X and 9_4_X IBs but for Sundays or where new updates are added.

**Comment by mrodozov** [comment]
@fabiocos I hope no problems will emerge. I'll merge and start the IBs

**Comment by mrodozov** [comment]
The IBs are building

**Comment by fabiocos** [comment]
@mrodozov it does what it was supposed to do, see https://github.com/cms-sw/cmssw/issues/26483 and https://github.com/cms-sw/cmssw/issues/26482

**Comment by fabiocos** [comment]
@mrodozov do you know when the file https://cmssdt.cern.ch/SDT/cgi-bin/ReleasesXML is updated? When I see the latest builds appearing as production, I will revert this PR and make usual builds with slc6 with production architecture

**Comment by fabiocos** [comment]
@mrodozov ok, they have appeared, I now revert this PR to its original state, and make an slc6 build

**Pull request merged**
