### PR TITLE
Add scripts to handle Spack installation; generate additional catalog entries for spack

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by smuzaffar** [comment]
for spack it generates these entries
```
/spack/share
/spack/share/data-L1Trigger-L1TMuon
/spack/share/data-GeneratorInterface-EvtGenInterface
/spack/share/data-MagneticField-Interpolation-*
/spack/*-*-*/*-*-*
/spack/*-*-*/*-*/blackhat-*
/spack/*-*-*/*-*/boost-*
/spack/*-*-*/*-*/cuda-*
/spack/*-*-*/*-*/geant4-*
/spack/*-*-*/*-*/G4EMLOW-*
/spack/*-*-*/*-*/herwigpp-*
/spack/*-*-*/*-*/madgraph5amc-*
/spack/*-*-*/*-*/py2-pippkgs-*
/spack/*-*-*/*-*/py2-pippkgs_depscipy-*
/spack/*-*-*/*-*/sherpa-*
/spack/*-*-*/*-*/rivet-*
/spack/*-*-*/*-*/cms
/spack/*-*-*/*-*/lcg
/spack/*-*-*/*-*/root
/spack/*-*-*/*-*/cmssw/CMSSW_*/src
/spack/*-*-*/*-*/cmssw/CMSSW_*
/spack/*-*-*/*-*/cmssw-patch/CMSSW_*/src
/spack/*-*-*/*-*/cmssw-patch/CMSSW_*
```

do these look correct? what are 
```
/spack/*-*-*/*-*/cms
/spack/*-*-*/*-*/lcg
/spack/*-*-*/*-*/root
/spack/*-*-*/*-*/cmssw
```

**Comment by smuzaffar** [comment]
looks like we already have software installed under `/cvmfs/cms-ib.cern.ch/spack` without `/cvmfs/cms-ib.cern.ch/.cvmfsdirtab` containing entries for `/spack` . That explains why IBs installation was very slow. We now have a large top level catelog  :-(
```
WARNING: catalog at / has more than 200000 entries (582803). Large catalogs stress the CernVM-FS transport infrastructure. Please split it into nested catalogs or increase the limit.
```

**Comment by smuzaffar** [comment]
> @smuzaffar I think that bootstrap, build and install scripts should stay in (move back to) cms-spack-repo, while cms-bot should contain generic scripts (cvmfsInstall.sh and singBuild.sh) that call the scripts from cms-spack-repo.

no objections

**Comment by iarspider** [comment]
I have updated the script generating dirtab, the new structure is:
```
/spack/share
/spack/share/data-l1trigger-l1tmuon
/spack/share/data-generatorinterface-evtgeninterface
/spack/share/data-magneticfield-interpolation-*
/spack/*-*-*/*-*/blackhat-*
/spack/*-*-*/*-*/boost-*
/spack/*-*-*/*-*/cuda-*
/spack/*-*-*/*-*/geant4-*
/spack/*-*-*/*-*/g4emlow-*
/spack/*-*-*/*-*/herwig7-*
/spack/*-*-*/*-*/madgraph5amc-*
/spack/*-*-*/*-*/sherpa-*
/spack/*-*-*/*-*/rivet-*
/spack/*-*-*/*-*/root-*
/spack/*-*-*/*-*/cmssw/CMSSW_*/src
/spack/*-*-*/*-*/cmssw/CMSSW_*
/spack/*-*-*/*-*/cmssw-patch/CMSSW_*/src
/spack/*-*-*/*-*/cmssw-patch/CMSSW_*
```

**Comment by iarspider** [comment]
@smuzaffar let's merge as is, I can move the scripts around in a separate PR.

**Comment by smuzaffar** [comment]
still needs updates but lets get it merged so that at least it can break the large cvmfs catelog

**Pull request merged**
