### PR TITLE
adding histogram and jr test tally info

### PR DESCRIPTION
**Pull request by davidlange6**
this is a bit more involved, so I'll try to watch for failing comparisons. adding some details about histogram comparisons (from the logs) and the JR tests (counting pngs). Still to do is to make a short summary..

### CODE REVIEW

**Comment by kpedro88** [comment]
@davidlange6 I just noticed these printouts in a CMSSW PR thread. Will this effort be coupled with removal of frequently/always-failing comparison plots from consideration (especially TimerService, but there are others), so the number of failures is more informative? (There's also a problem somewhere in the comparison code, in which certain histograms can be tagged as failing (BinToBin = 0.0) when both new and ref have 0 entries. I'm not sure where or how to fix it.)

**Comment by davidlange6** [comment]
> On Apr 6, 2017, at 12:27 PM, Kevin Pedro <notifications@github.com> wrote:
> 
> @davidlange6 I just noticed these printouts in a CMSSW PR thread. Will this effort be coupled with removal of frequently/always-failing comparison plots from consideration (especially TimerService, but there are others), so the number of failures is more informative? (There's also a problem somewhere in the comparison code, in which certain histograms can be tagged as failing (BinToBin = 0.0) when both new and ref have 0 entries. I'm not sure where or how to fix it.)
> 

its not terribly high on my personal priority list, no. But obviously that could be done.

**Comment by davidlange6** [comment]
> On Apr 6, 2017, at 12:27 PM, Kevin Pedro <notifications@github.com> wrote:
> 
> @davidlange6 I just noticed these printouts in a CMSSW PR thread. Will this effort be coupled with removal of frequently/always-failing comparison plots from consideration (especially TimerService, but there are others), so the number of failures is more informative? (There's also a problem somewhere in the comparison code, in which certain histograms can be tagged as failing (BinToBin = 0.0) when both new and ref have 0 entries. I'm not sure where or how to fix it.)

so I looked at what should happen with new and ref have 0 entries. if there are no entries between bin 1 and bin # of bins, the test should declare the histograms are in agreement.

I looked at one test "failure" - where all of the AlCaReco/SiStrip/MechanicalView histograms fail (nearly). There the one of the two histograms has plenty of entries. So thats a real failure. Now, why this workflow... and why this alca histograms, I dunno.

**Comment by kpedro88** [comment]
The one I always notice is `HLT__Higgs_PhotonJet_trigvsnvtx`, e.g. in workflow 9.0.

I think the SiStrip failures are something else...

**Comment by slava77** [comment]
On 4/6/17 9:17 PM, Kevin Pedro wrote:
> The one I always notice is |HLT__Higgs_PhotonJet_trigvsnvtx|, e.g. in
> workflow 9.0.

check for nans

**Comment by davidlange6** [comment]
indeed, checking one example, the log file reports NANs.  its not obvious to me how this histogram get NANs, but I can add some information to the log to help (via cmssw pr)

**Comment by slava77** [comment]
On 4/7/17 10:55 AM, David Lange wrote:
> indeed, checking one example, the log file reports NANs. its not obvious
> to me how this histogram get NANs, but I can add some information to the
> log to help (via cmssw pr)

this may be helpful

https://twiki.cern.ch/twiki/bin/viewauth/CMS/RecoIntegration#Compare_outputs_DQM_style
look for "stripDQM"
this/similar cleanup was a part of our PR checkout for a few years


>

**Comment by davidlange6** [comment]
ok, here is the problem with that histogram.

https://cmssdt.cern.ch/lxr/source/DQMOffline/Trigger/src/HigPhotonJetHLTOfflineSource.cc#0325

**Comment by kpedro88** [comment]
submitted https://github.com/cms-sw/cmssw/pull/18258 to fix it

**Pull request merged**
