### PR TITLE
Added support for changed DQM bbb comparison tool

### PR DESCRIPTION
**Pull request by andrius-k**
Added support to [recently introduced changes](https://github.com/cms-sw/cmssw/pull/26848) in the DQM bin by bin comparison tool.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@andrius-k , did it work ? As I wrote https://github.com/cms-sw/cmssw/pull/26848#issuecomment-495493824 , we need to backport https://github.com/cms-sw/cmssw/pull/26848 for 10.6.X too.

**Comment by andrius-k** [comment]
@smuzaffar Yes, it works. Could we please merge it as soon as possible because the new code is not compatible with the old invocation and now it's crashing.

**Comment by andrius-k** [comment]
@smuzaffar I will of course prepare a backport to 10.6.X as well.

**Pull request merged**
