### PR TITLE
Jenkins auto-retry job: retry on singularity mount errors

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by smuzaffar** [comment]
I am not sure if this is the right solution for these errors. This only happens when we run container in side a container...right? Did we try to reproduce the issue manually on a node where it happened?

**Comment by iarspider** [comment]
@smuzaffar 
> This only happens when we run container in side a container...right? 
no, even when just starting a container

> Did we try to reproduce the issue manually on a node where it happened?
the latest failures (failed to mount /afs/cern.ch/home/c/cmsbuild) I managed to reproduce on lxplus700, but it was later blacklisted by a sanity check job. I didn't check the other failure (failed to mount tnsnames.ora).

**Comment by smuzaffar** [comment]
can you please point me to the jenkins log for this failed job?

**Comment by smuzaffar** [comment]
ok, I can reproduce it on lxplus700
```
-bash-4.2$ cmssw-el8
FATAL:   container creation failed: mount hook function failure: mount /afs/cern.ch/user/c/cmsbuild->/var/apptainer/mnt/session/afs/cern.ch/user/c/cmsbuild error: while mounting /afs/cern.ch/user/c/cmsbuild: destination /var/apptainer/mnt/session/afs/cern.ch/user/c/cmsbuild doesn't exist in container
```

**Comment by iarspider** [comment]
@smuzaffar "failed to mount /afs/...": https://cmssdt.cern.ch/jenkins/job/ib-run-igprof/44287, "failed to mount tnsnames.ora": https://cmssdt.cern.ch/jenkins/job/ib-run-qa/57778/consoleFull ([RelVal](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_1_ROOT6_X_2023-03-02-2300/pyRelValMatrixLogs/run/10804.31_SingleGammaPt10+2018_photonDRN/step3_SingleGammaPt10+2018_photonDRN.log#/34))

**Comment by smuzaffar** [comment]
@aandvalenzuela , do you have any objection?

**Comment by smuzaffar** [comment]
lets get this in. @aandvalenzuela , is the re-try job going to get the change automaticall or do you have to manually update it on jenkins server?

**Comment by aandvalenzuela** [comment]
Sorry for the delay, I did not see the ping.
Yes, it gets updates automatically. It has been running fine since the merge :)

**Pull request merged**
