### PR TITLE
Make CLANG IBs to use unmodified CMSSW stable branch

### PR DESCRIPTION
**Pull request by davidlt**
Currently pre-3.6 Clang is only available in DEVEL IBs. Until
merged to stable CMSDIST branch we should use CMSDIST next branch
with new Clang.

Also make sure that Clang IBs are using plain CMSSW without any
additional patches, i.e., CMSSW stable branch.

Signed-off-by: David Abdurachmanov <davidlt@cern.ch>

### CODE REVIEW

**Comment by ktf** [comment]
We should have a few builds with this and then kill the _CLANG_X branch, BTW...

**Comment by davidlt** [comment]
If you are happy with loosing the history of CLANG_X branch, I am OK.

**Comment by ktf** [comment]
So long and thanks for all the fish.. ;)

**Comment by ktf** [comment]
So long and thanks for all the fish..

**Pull request merged**
