### PR TITLE
Add phase-2 D88 geom wf to profileRunner.py

### PR DESCRIPTION
**Pull request by clacaputo**
This PR adds wf `39634.21` in `profileRunner.py` to include phase-2 D88 detector in profiling jobs

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
Hi @clacaputo,
Just for my education: is there any special way to test this?
I have seen the Jenkins test `release-run-reco-profiling` has been used in some older PRs for that purpose.

Many thanks!

**Comment by clacaputo** [comment]
> Hi @clacaputo, Just for my education: is there any special way to test this? I have seen the Jenkins test `release-run-reco-profiling` has been used in some older PRs for that purpose.
> 
> Many thanks!

Hi @aandvalenzuela , honestly I'm not familiar with testing PR on cms-bot, sorry

**Comment by clacaputo** [comment]
Hi @aandvalenzuela , maybe with this change here [1], it is possible to trigger the usual test+profiling. The bot should now pick the new workflow `39634.21`


[1] https://github.com/cms-sw/cms-bot/pull/1799/files#diff-ac01d7ab9f36c6274896d7d29e19a1b7e7ceaa91c6decd957a0777c074596d98R3

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by clacaputo** [comment]
enable profiling

**Comment by aandvalenzuela** [comment]
Hi @clacaputo, 
Yes, I can see the new workflow `39634.21` has been considered for the tests and everything run successfully.
Do you agree to merge?

**Comment by aandvalenzuela** [comment]
+1

**Comment by aandvalenzuela** [comment]
Hi @clacaputo,

This new workflow `39634.21` is producing failures due to "Undefined workflow" in `igprof` for `CMSSW_11_3_X`, `CMSSW_12_0_X` and `CMSSW_12_1_X`. Does it need to run also for these releases? Let me know if you prefer to revert the changes of this PR or, if you prefer, I can open a new issue for this.

Thank you,
Andrea.

**Pull request merged**
