### PR TITLE
Add category xpog with no package associated for AN release branch management

### PR DESCRIPTION
**Pull request by fabiocos**
As agreed, a new empty category "xpog" with no CMSSW package associated is added, and the present XPOG coordinators are associated as responsible. This addition is intended to support the forthcoming AN release branch management, where the integration will be mostly done based on agreement from the XPOG coordinators (+ basic technical tests).

### CODE REVIEW

**Comment by fabiocos** [comment]
@smuzaffar I added the new empty category and the associated responsible people, is anything more needed to have the possibility to assign a PR or an issue?
I must do something wrong in the syntax of categories_map.py, but I do not see what...

**Comment by fabiocos** [comment]
@smuzaffar thanks, but why is that syntax working at line 2 for "externals"?

**Comment by smuzaffar** [comment]
test_watcher.py was match the empty string to the package regexp. I updated the PR to have empty list instead of list with one empty string

**Comment by smuzaffar** [comment]
xpog category should be recognized now. Can you try doing "assign xpog" to some cmssw PR to see if it works and then if needed you can do "unassign xpog"

**Pull request merged**
