### PR TITLE
Add test wf 23234.0 to the comparison list

### PR DESCRIPTION
**Pull request by fabiocos**
in response to cms-sw/cmssw#28487

### CODE REVIEW

**Comment by fabiocos** [comment]
@slava77 FYI as discussed in #1228

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> @slava77 FYI as discussed in #1228

thank you for making the PR.
I think that this can be merged after the tests are done

**Comment by slava77** [comment]
@fabiocos 
in the meantime I found a problem in my previous update of the mapping.
So, I made a PR, including changes from this one in #1230 
I propose to use that PR instead.

**Comment by smuzaffar** [comment]
closing in favor of https://github.com/cms-sw/cms-bot/pull/1230

**Pull request closed without merging**
