### PR TITLE
Remove redundant clang-tidy checks. The ESR::get check is implemented in a static analyzer check.

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
please test with https://github.com/cms-sw/cmssw/pull/34213

**Comment by gartung** [comment]
abort

**Comment by gartung** [comment]
please test with cms-sw/cmssw#34213

**Comment by gartung** [comment]
please test with https://github.com/cms-sw/cmssw/pull/34224

**Comment by gartung** [comment]
@makortel the report no longer has the clang tidy lines in it
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-a344fd/16199/summary.html

**Comment by makortel** [comment]
The PR message https://github.com/cms-sw/cmssw/pull/34213#issuecomment-867043961 looks good now, thanks!

**Pull request merged**
