### PR TITLE
Another fix for static analyzer script.

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
@mrodozov @smuzaffar

**Comment by gartung** [comment]
please test with https://github.com/cms-sw/cmssw/pull/33870

**Comment by mrodozov** [comment]
please test with cms-sw/cmssw#33870, cms-sw/cmssw#33875

**Comment by mrodozov** [comment]
+externals
we need at least 33870

**Comment by qliphy** [comment]
+1

**Pull request merged**
