### PR TITLE
Add step5 in the file size comparison

### PR DESCRIPTION
**Pull request by silviodonato**
See https://github.com/cms-sw/cmssw/issues/34136
cc @jpata

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- enable_test = profiling

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@silviodonato , @jpata can you please check profiling results for file size comparison ?

**Comment by silviodonato** [comment]
@smuzaffar no, it is not yet ok.

I'm missing something because in the jenkins log
[log_profiling_jenkins.txt](https://github.com/cms-sw/cms-bot/files/6701184/log_profiling_jenkins.txt)

I see that it runs
```
20:17:15   cmsDriver.py step5  --conditions auto:phase1_2021_realistic -n 10 --era Run3 --eventcontent NANOEDMAODSIM --filein file:step4.root -s NANO --datatier NANOAODSIM --geometry DB:Extended --number=20 --nThreads=1 --customise=HLTrigger/Timer/FastTimer.customise_timer_service_singlejob --no_exec --dirin=/data/cmsbld/jenkins/workspace/ib-run-pr-profiling --dirout=/data/cmsbld/jenkins/workspace/ib-run-pr-profiling --fileout file:step5.root  > step5_TTbar_14TeV+2021PU_ProdLike+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoPU+MiniAODPU+Nano.log  2>&1
```

but the edmEventSize is skipped for step5
```
20:56:20  + edmEventSize -v /data/cmsbld/jenkins/workspace/ib-run-pr-profiling/step3.root
20:56:28  + edmEventSize -v /data/cmsbld/jenkins/workspace/ib-run-pr-profiling/step4.root
```

even if I added step5 in all steps using `edmEventSize -v`:
```
$ git grep "edmEventSize -v"

comparisons/compareProducts.sh:    edmEventSize -v ${fA} > ${os}
comparisons/compareProducts.sh:    edmEventSize -v ${fB} > ${ns}
pr_testing/run-pr-profiling.sh:    edmEventSize -v $WORKSPACE/step3*.root > step3_sizes_${PROFILING_WORKFLOW}.txt || true
pr_testing/run-pr-profiling.sh:    edmEventSize -v $WORKSPACE/step4*.root > step4_sizes_${PROFILING_WORKFLOW}.txt || true
pr_testing/run-pr-profiling.sh:    edmEventSize -v $WORKSPACE/step5*.root > step5_sizes_${PROFILING_WORKFLOW}.txt || true
run-ib-igprof:      edmEventSize -v ${hpwf}_*/${s}.root> ${s}_sizes_${hpwf}.txt
```

Actually I don't know which part of the code runs
```
edmEventSize -v /data/cmsbld/jenkins/workspace/ib-run-pr-profiling/step3.root
```

@jpata do you know?

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
I've included some additional changes in cms-cmpwg/profiling, see https://github.com/cms-cmpwg/profiling/pull/3

**Comment by silviodonato** [comment]
please test
I've added a small change to run edmEventSize even if there is no IB reference (for testing only)

**Comment by silviodonato** [comment]
please test

**Comment by jpata** [comment]
looks to me the generated file step5_sizes_11834.21.txt is empty: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23c006/16288/profiling/11834.21/

**Comment by silviodonato** [comment]
please test
(I've added https://github.com/cms-cmpwg/profiling/pull/3/commits/b2b60f2dc67f135092618dd541f9ec963a121ce2 )

**Comment by silviodonato** [comment]
@jpata @smuzaffar ok I see the step5 sizes:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23c006/16366/profiling/11834.21/step5_sizes_11834.21.txt

The comparison wrt the IB is still not available because https://github.com/cms-cmpwg/profiling/pull/3 needs to included in the IB test.

I suggest to merge https://github.com/cms-cmpwg/profiling/pull/3 first and then test again of this PR.

(please note that I removed the temporary code used for testing https://github.com/cms-sw/cms-bot/pull/1567/commits/7c98ec261850281ae931eadd3a2ee674d512903b)

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
@cms-sw/xpog-l2 in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23c006/16403/profiling/11834.21/products_nanoAOD_sizes_compare_11834.21.txt we have finally the comparison of the nanoAOD file sizes.

Unfortunately with https://github.com/cms-cmpwg/profiling/pull/3 I've also broken the profiling test of `23434.21` (`23434.21` has no `step5`).  I've prepared https://github.com/cms-cmpwg/profiling/pull/4 which should fix the problem.

**Comment by silviodonato** [comment]
please test
The problem in `23434.21` has been fixed by https://github.com/cms-cmpwg/profiling/pull/4,
this time everything should be ok.

**Comment by silviodonato** [comment]
please test
the previous test picked `CMSSW_12_0_X_2021-07-05-1100` `23434.21` which is still broken. 
image
`CMSSW_12_0_X_2021-07-05-1100` and later are fixed

https://cmssdt.cern.ch/jenkins/job/ib-run-profiling/

**Comment by silviodonato** [comment]
abort

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
the profiling results looks ok https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23c006/16544/profiling/
I see `edmEventSize Comparison nanoAOD output. ` in `11834.21`
@smuzaffar feel free to merge this PR
cc @jpata  @cms-sw/xpog-l2

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
