### PR TITLE
Create json files for build externals

### PR DESCRIPTION
**Pull request by tulamor**

### CODE REVIEW

**Comment by smuzaffar** [comment]
@tulamor , script failed with error
```
10:17:18 + timeout 60 /data/cmsbld/jenkins/workspace/build-any-ib/cms-bot/create_json.py -logfile w/cmsswtoolconf.log -jsonfile w/CMSSW_5_3_X_2020-05-31-2300_slc6_amd64_gcc472_deps.json
10:17:18 Traceback (most recent call last):
10:17:18   File "/data/cmsbld/jenkins/workspace/build-any-ib/cms-bot/create_json.py", line 6, in <module>
10:17:18     from argparse import ArgumentParser
10:17:18 ImportError: No module named argparse
```

**Comment by tulamor** [comment]
Could you please provide access to cmsbuild machine?

**Comment by smuzaffar** [comment]
you do not need access to build machine. We run under singularity, so just (on lxplus) run cmssw/slc6 and test your script under that

**Comment by tulamor** [comment]
> @tulamor , script failed with error
> 
> ```
> 10:17:18 + timeout 60 /data/cmsbld/jenkins/workspace/build-any-ib/cms-bot/create_json.py -logfile w/cmsswtoolconf.log -jsonfile w/CMSSW_5_3_X_2020-05-31-2300_slc6_amd64_gcc472_deps.json
> 10:17:18 Traceback (most recent call last):
> 10:17:18   File "/data/cmsbld/jenkins/workspace/build-any-ib/cms-bot/create_json.py", line 6, in <module>
> 10:17:18     from argparse import ArgumentParser
> 10:17:18 ImportError: No module named argparse
> ```

@smuzaffar The argparse module was added **since** Python 2.7 where build machines uses version 2.6.6

**Comment by smuzaffar** [comment]
we use python from system and on SLC6 (RHEL6) default python version if 2.6 so we have to make sure that our scripts works for python >=2.6

**Pull request merged**
