### PR TITLE
Update name of pull request memory profiling script.

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
please test

**Comment by smuzaffar** [comment]
@gartung , do you need to enable profiling test for this PR?

**Comment by gartung** [comment]
enable profiling

**Comment by smuzaffar** [comment]
please test

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
@smuzaffar can this be merged

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
