### PR TITLE
docker_launcher: create a separate voms proxy file per job ...

### PR DESCRIPTION
**Pull request by iarspider**
to avoid overwriting it - prevents errors like
```
DAS error: b'2024/01/08 01:25:37 ERROR failed to parse X509 proxy: crypto/tls: failed to parse key: asn1: syntax error: data truncated\n'
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
@iarspider , thanks for looking in to this.
Instead of using 
```
-out $WORKSPACE/x509up_u`id -u`
```
why not just set 
```
export X509_USER_PROXY=$WORKSPACE/x509up_u`id -u`
```

and then all `voms-proxy-*`  will use the file pointing to this

**Comment by iarspider** [comment]
@smuzaffar this is how it's done [here](https://github.com/cms-sw/cms-bot/blob/master/DMWM/setup-secrets.sh#L21). If setting `X509_USER_PROXY` in advance works, then I'll do it.

**Comment by smuzaffar** [comment]
yes setting `X509_USER_PROXY` works ( at least  voms-proxy-init uses it to generate dump the new proxy). testing it by setting `X509_USER_PROXY` then using `voms-proxy-init` and `voms-proxy-info`

**Comment by iarspider** [comment]
> yes setting `X509_USER_PROXY` works ( at least voms-proxy-init uses it to generate dump the new proxy). testing it by setting `X509_USER_PROXY` then using `voms-proxy-init` and `voms-proxy-info`

It doesn't work for `voms-proxy-destroy`, but we don't use it anywhere.

**Comment by smuzaffar** [comment]
can you also move https://github.com/cms-sw/cms-bot/blob/d78dc1ac9e17e99966709dbffcfcb41985a05ba5/docker_launcher.sh#L52  above the `export X509_USER_PROXY...`

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
> X509_USER_PROXY doesn't work for `voms-proxy-destroy`, but we don't use it anywhere.

looks like a known issue https://github.com/italiangrid/voms-clients/issues/26 . Lets hope they include the fix https://github.com/italiangrid/voms-clients/pull/27 in next release

**Pull request merged**
