### PR TITLE
reco comparisons: 2021 FastSim workflows 13234, 13434

### PR DESCRIPTION
**Pull request by slava77**
the short matrix was updated in cms-sw/cmssw#38660 and merged in CMSSW_12_5_X_2022-07-20-2300.

This PR updates the workflow map file to correctly run the reco FWLite-based comparisons and get rid of the warning appearing in the PR comparisons summary.

@cms-sw/reconstruction-l2

### CODE REVIEW

**Comment by slava77** [comment]
The comparison folders showed up as expected


[all_OldVSNew_TTbarFS14TeV2021wf13234p0/](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_5_X_2022-07-21-1100+950d37/51730/validateJR/all_OldVSNew_TTbarFS14TeV2021wf13234p0/)	2022-07-21 20:28 	- 	 
[all_OldVSNew_TTbarFS14TeVPU2021wf13434p0/](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_5_X_2022-07-21-1100+950d37/51730/validateJR/all_OldVSNew_TTbarFS14TeVPU2021wf13434p0/)	2022-07-21 20:28 	- 	 

The contents of the job logs seem as expected as well.

**Comment by aandvalenzuela** [comment]
Hi @slava77,

Can we merge then? Many thanks

**Comment by clacaputo** [comment]
Hi @slava77 , thanks a lot for updating it

**Comment by slava77** [comment]
> Hi @slava77,
> 
> Can we merge then? Many thanks

yes, but formally someone currently a reco L2 needs to confirm. I suppose the last message from @clacaputo is doing that implicitly.

**Comment by clacaputo** [comment]
> > Hi @slava77,
> > Can we merge then? Many thanks
> 
> yes, but formally someone currently a reco L2 needs to confirm. I suppose the last message from @clacaputo is doing that implicitly.

Ah! I didn't see a `reconstructio-pending` label so I've supposed no formal sign from my side was needed

**Comment by clacaputo** [comment]
+reconstruction

**Comment by aandvalenzuela** [comment]
+1

**Pull request merged**
