### PR TITLE
Update phase2 profiling workflow to 35234.21

### PR DESCRIPTION
**Pull request by gartung**
D77 ttbar prodlike PU

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- enable_test = profiling

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@gartung this is good to go in. By the way why to change the workflow, was there a request to use for the change?

**Comment by gartung** [comment]
Yes. @perrotta suggested it.

**Comment by smuzaffar** [comment]
+externals

**Comment by perrotta** [comment]
> Yes. @perrotta suggested it.

Thank you Patrick, and Shahzad

To elaborate a bit further, we realized together with @cms-sw/reconstruction-l2  and @cms-sw/upgrade-l2 conveners that the D49 geometry used for profiling the phase2 workflows in the IBs and in the PR tests was not the currently preferred one for upgrade studies and developments (in particular by MTD, for which @fabiocos originally posed the question). Reco uses D76 for its performance tests, D77 is used in RelVals (and it will move soon to D88). D88 samples with PU will only become available after 12_3_0_pre5, therefore D77 looks now the best possible benchmark for performance measurements also for the IBs, before moving to D88.

**Pull request merged**
