### PR TITLE
Remove temporary symlinks

### PR DESCRIPTION
**Pull request by iarspider**
The following scripts doesn't appear to be used:

* cms-jenkins-api
* es-cleanup-indexes
* es-reindex
* forward-pull-requests
* generate-json-performance-charts
* generate-performance-summary
* get-git-tags
* merge-pull-request
* new-release-cycle
* process-error-reports
* report-cmsdist-pull-request-results
* scram-package-monitor-sender
* scram-package-monitor-timestamps
* tag-ib
* updateVOTags

### CODE REVIEW

**Comment by smuzaffar** [comment]
thanks @iarspider , can you please check https://github.com/cms-sw/cmssdt-web and https://github.com/cms-sw/cms-sw.github.io repositories for any ref to these scripts? I hope you have already searched all jenkins jobs for these

**Comment by iarspider** [comment]
@smuzaffar I have checked jobs on cmsjenkins03. I will check repositories mentioned.

**Comment by iarspider** [comment]
Black errors are handled in #2144, can factor them out into a separate PR.

**Comment by smuzaffar** [comment]
> Black errors are handled in #2144, can factor them out into a separate PR.

yes it is better to factor these out and create a separate PR

**Comment by smuzaffar** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
lets merge it and keep an eye on various jobs

**Pull request merged**
