### PR TITLE
fixed categories for qliphy

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
@qliphy , please note that once this is merged then you will have following right
- L2 for Generators
- L2 for Operations
- Release manager
So in future when you do `+1` then this means you will sign all the above categories. In case you want to sign only for a specific category then please use `+generators` or `+operations` or `+orp`

**Comment by qliphy** [comment]
@smuzaffar  thanks!  Silvio also just reminded me on this.

**Comment by smuzaffar** [comment]
@qliphy , can you please try to comment `+1` on this Pr to see if cmsbot signs it for ORP?

**Comment by qliphy** [comment]
+1

**Comment by smuzaffar** [comment]
great, looks all OK

**Pull request merged**
