### PR TITLE
Adding new L2s for EGM and PF in `categories.py`

### PR DESCRIPTION
**Pull request by swagata87**
Adding new L2 convenors for EGM POG and PF group. 
The old L2s are not removed as we are in overlap period until end of August.
FYI @cms-sw/egamma-pog-l2 and @cms-sw/pf-l2, @RSalvatico

### CODE REVIEW

**Comment by smuzaffar** [comment]
@cms-sw/pf-l2 and @RSalvatic any objection ?

**Comment by RSalvatico** [comment]
No objection!

**Comment by swagata87** [comment]
After talking to continuing PF L2 @kdlong, I removed Juska as he left CMS and stepped down from PF L2 few weeks ago.
And I added Riccardo Bellan @bellan another incoming PF L2. 
For the record, the incoming L2 list can be found here: https://indico.cern.ch/event/1254948/contributions/5271908/attachments/2630936/4550748/CB143%20Apr%202023%20.pdf

**Comment by smuzaffar** [comment]
@swagata87 , looks like your addition to [pf](https://github.com/cms-sw/cms-bot/blob/master/categories.py#L117) was not taken in to account by bot as it was overridden by your entry [egamma-pog](https://github.com/cms-sw/cms-bot/blob/master/categories.py#L119) . There should only be one entry for each user.  If you should be part of both `pf` and `egamma-pog` then please let me know or open a pr with `"swagata87":        ["egamma-pog", "pf"],`

**Comment by swagata87** [comment]
Thank you @smuzaffar. I would like to be part of only `pf` team; and this is a good time for me to leave the `egamma` team as my term has ended. Could you kindly make this adjustment?

**Pull request merged**
