### PR TITLE
Update watched packages for user riga.

### PR DESCRIPTION
**Pull request by riga**
Hi,
I'd like to update the list of packages that I watch, so I updated my list in the watchers.yml file.
Cheers!

### CODE REVIEW

**Comment by riga** [comment]
Hey @mrodozov ,
do you know when this change becomes active? I'm somehow still automatically subscribed to a lot of PRs, resulting in tons of notifications ;)

**Comment by mrodozov** [comment]
I should've become effective right away, I have to check what the bot is doing

**Comment by riga** [comment]
Thank you!

**Comment by mrodozov** [comment]
So I have one assumption - if your username was still in the watchers when the PR/issue was open, well then it's still there until the PR is merged/closed etc and every time you'll get the notifications. 
There would be a problem for new PRs (after this was merged) if the bot still adds you as a watcher
Lets see if your user is in the new PRs from the removed categories.

**Comment by riga** [comment]
> Lets see if your user is in the new PRs from the removed categories.

I think I still get notifications. E.g. I was notified about # 32180 (added the space to prevent cross linking) this morning, although I'm not sure if I've ever had that in my watched packages.

**Comment by smuzaffar** [comment]
@riga, so you were notificed about cms-sw/cmssw#32180 ? As your name is not explicitly mentioned on the PR, so I guess you have added cms-sw/cmssw to your watch list and you are getting all the notifications?

**Comment by riga** [comment]
You are absolutely right ... I probably clicked on that by accident. Now my inbox can breathe again ;)
Sorry for the noise.

**Pull request merged**
