### PR TITLE
add timestamps to progress messages in run-pr-comparisons

### PR DESCRIPTION
**Pull request by slava77**
date timestamps are added to aid occasional tracking or debugging of the comparisons jobs

### CODE REVIEW

**Comment by slava77** [comment]
looking at https://meter.cern.ch/public/_plugin/kibana/#/dashboard/temp/AV2fkZnFnDFcZnuewq3f

screen shot 2017-08-01 at 2 52 56 pm
It seems to me that the overload comes from the DQM comparisons (mostly from the "default")

- validateJR is supposed to use ``` _NPROCESSORS_ONLN ``` and exit only after it is done with all. run-pr-comparisons is running validateJR in foreground. 
    - these start at 17:31 and finish around 17:43 with a max load of about 8
-  default comparisons  is started after JR in parallel in a single job per output to compare. The latest short matrix has 25 workflows (although it looks like only 22 are actually running). If I understand correctly, the code is hard-coded to occupy 4 threads https://github.com/cms-sw/cmssw/blob/master/Utilities/RelMon/python/dqm_interfaces.py#L448. So, this can run up to 88 threads and should explain the peak load.
    - these start at 17:43 and if I understand run-pr-comparisons correctly, the job waits for all to finish, which would be up to 20:08. The peak load is around 60, lower than 88, but that was probably limited by the system
- alternative comparisons run last and they are wrapped in a script that also starts them all in parallel. Here we expect a peak load of 22, compared to 19 shown in the monitoring, which is in good agreement.
    - the alternative comparisons start at 20:08 and finish at around 20:55

From the above analysis it looks like the "default comparisons" is the main problem (it is the slowest and it overloads the nodes).

SO, I'm hoping for a confirmation of the above based on this PR.
If the issue with the relmon is confirmed, there will need to be a follow up wither on cms-bot side or on CMSSW.

**Comment by slava77** [comment]
thanks for merging, but the change did not work
e.g. https://cmssdt.cern.ch/jenkins/job/compare-root-files-short-matrix/21731/consoleFull
I see 
``` Start JR comparison at `date` ```

the parser does not recognize the back-quotes as an executable action item.
What should be used instead?

**Comment by smuzaffar** [comment]
I already fixed that https://github.com/cms-sw/cms-bot/pull/882#issuecomment-319697035 (few mins ago). One should use double quotes :-)

**Comment by slava77** [comment]
On 8/2/17 7:56 AM, Malik Shahzad Muzaffar wrote:
> I already fixed that #882 (comment)
> <https://github.com/cms-sw/cms-bot/pull/882#issuecomment-319697035> (few
> mins ago). One should use double quotes :-)

thanks.
I'll check what comes out in some PR test later today.

**Comment by slava77** [comment]
Some notes from tests of https://github.com/cms-sw/cmssw/pull/20029
https://cmssdt.cern.ch/jenkins/job/compare-root-files-short-matrix/21749/

- started Aug 3, 2017 12:27:00 AM
-  Took 3 hr 57 min on cmsbuild08

Details from printouts with dates
- Set up release area at Thu Aug  3 00:27:07 CEST 2017
- [start download] at Thu Aug  3 00:27:16 CEST 2017
- Finished downloading files at Thu Aug  3 00:39:50 CEST 2017:
- Start JR comparison at Thu Aug  3 00:39:54 CEST 2017
- Finished with JR comparison at Thu Aug  3 00:52:55 CEST 2017:
- Started with default comparison at Thu Aug  3 00:52:55 CEST 2017
- Finished with default comparison at Thu Aug  3 03:16:53 CEST 2017
- Started with alternative comparison at Thu Aug  3 03:18:34 CEST 2017
- Finished with alternative comparison at Thu Aug  3 03:35:44 CEST 2017:
- All done at Thu Aug  3 04:24:16 CEST 2017

So, what we have is
- startup is 10 s
- copy inputs 12.5 mins
- run JR comparisons 13 mins
- run relmon comparisons 2 h 24 mins
- run alternative comparisons 17 mins

This confirms that the slowest part is running the default comparisons (relmon). It is also pushing the machine load to some extremes.

What is a node efficiency when its load average is a factor of 5-8 over the number of cores and each active thread is doing some python calls and also file I/O?

Perhaps the starting point could be to start the relmon jobs in a sleep loop that checks loadavg to be below n processors.
@smuzaffar do you have time to try this out?

**Comment by smuzaffar** [comment]
comparison job https://cmssdt.cern.ch/jenkins/job/compare-root-files-short-matrix/21752/console is now using it and I see that three workflows [a] and taking took much time (over 1.5 hours and counting). I also see a lot of segmentation voilation going on 
```
Histogram efficiencyVertex differs: nok: 4.0 ntot: 15
This comparison failed 0.266667

 *** Break *** segmentation violation

 *** Break *** segmentation violation
grep 'segmentation violation'  /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/default-comparison/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017RelMonComp-10024.0.log  |wc -l
2356
```

[a]
```
 3487 11:16              |   \_ /bin/sh -ex /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/default-comparison/command-10024.0
 3494 11:16              |       \_ python /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_X_2017-07-31-1200/bin/slc6_amd64_gcc630/compare_using_files.py /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/files/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017 
 2026 12:50              |           \_ python /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_X_2017-07-31-1200/bin/slc6_amd64_gcc630/compare_using_files.py /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/files/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_ 
 2689 12:50              |           |   \_ sh -c /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/lcg/root/6.10.02/etc/gdb-backtrace.sh 2026 1>&2
 2715 12:50              |           |       \_ /bin/sh /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/lcg/root/6.10.02/etc/gdb-backtrace.sh 2026
 3303 12:50              |           |           \_ gdb --batch --eval-command=bt /proc/2026/exe 2026
 3304 12:50              |           |           \_ sed -n -e s,\x1B\[[0-9;]*[a-zA-Z],,g -e s/^(gdb) // -e /^#/p -e /^   /p -e s/\(^Thread.*\)/@\1/p
 3305 12:50              |           |           \_ tr @ \n
 2080 12:50              |           \_ [python] <defunct>
 2132 12:50              |           \_ python /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_X_2017-07-31-1200/bin/slc6_amd64_gcc630/compare_using_files.py /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/files/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_ 
 2676 12:50              |           |   \_ sh -c /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/lcg/root/6.10.02/etc/gdb-backtrace.sh 2132 1>&2
 2699 12:50              |           |       \_ /bin/sh /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/lcg/root/6.10.02/etc/gdb-backtrace.sh 2132
 3362 12:50              |           |           \_ gdb --batch --eval-command=bt /proc/2132/exe 2132
 3363 12:50              |           |           \_ sed -n -e s,\x1B\[[0-9;]*[a-zA-Z],,g -e s/^(gdb) // -e /^#/p -e /^   /p -e s/\(^Thread.*\)/@\1/p
 3364 12:50              |           |           \_ tr @ \n
 2163 12:50              |           \_ [python] <defunct>
32390 11:20              \_ /bin/sh -ex /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/cms-bot/run-pr-comparisons
32395 11:20              |   \_ /bin/sh -ex /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/default-comparison/command-10042.0
32407 11:20              |       \_ python /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_X_2017-07-31-1200/bin/slc6_amd64_gcc630/compare_using_files.py /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/files/10042.0_ZMM_13+ZMM_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HAR 
 3755 12:50              |           \_ python /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_X_2017-07-31-1200/bin/slc6_amd64_gcc630/compare_using_files.py /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/files/10042.0_ZMM_13+ZMM_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017 
 3764 12:50              |           |   \_ sh -c /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/lcg/root/6.10.02/etc/gdb-backtrace.sh 3755 1>&2
 3765 12:50              |           |       \_ /bin/sh /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/lcg/root/6.10.02/etc/gdb-backtrace.sh 3755
 3819 12:50              |           |           \_ gdb --batch --eval-command=bt /proc/3755/exe 3755
 3820 12:50              |           |           \_ sed -n -e s,\x1B\[[0-9;]*[a-zA-Z],,g -e s/^(gdb) // -e /^#/p -e /^   /p -e s/\(^Thread.*\)/@\1/p
 3821 12:50              |           |           \_ tr @ \n
 3758 12:50              |           \_ python /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_X_2017-07-31-1200/bin/slc6_amd64_gcc630/compare_using_files.py /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/files/10042.0_ZMM_13+ZMM_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017 
 3789 12:50              |           |   \_ sh -c /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/lcg/root/6.10.02/etc/gdb-backtrace.sh 3758 1>&2
 3790 12:50              |           |       \_ /bin/sh /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/lcg/root/6.10.02/etc/gdb-backtrace.sh 3758
 3830 12:50              |           |           \_ gdb --batch --eval-command=bt /proc/3758/exe 3758
 3831 12:50              |           |           \_ sed -n -e s,\x1B\[[0-9;]*[a-zA-Z],,g -e s/^(gdb) // -e /^#/p -e /^   /p -e s/\(^Thread.*\)/@\1/p
 3832 12:50              |           |           \_ tr @ \n
 3759 12:50              |           \_ [python] <defunct>
 3760 12:50              |           \_ [python] <defunct>
29366 11:21              \_ /bin/sh -ex /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/cms-bot/run-pr-comparisons
29368 11:21                  \_ /bin/sh -ex /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/default-comparison/command-10824.0
29372 11:21                      \_ python /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_X_2017-07-31-1200/bin/slc6_amd64_gcc630/compare_using_files.py /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/files/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018 
 3480 12:50                          \_ python /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_X_2017-07-31-1200/bin/slc6_amd64_gcc630/compare_using_files.py /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/files/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_ 
 3715 12:50                          |   \_ sh -c /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/lcg/root/6.10.02/etc/gdb-backtrace.sh 3480 1>&2
 3721 12:50                          |       \_ /bin/sh /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/lcg/root/6.10.02/etc/gdb-backtrace.sh 3480
 3784 12:50                          |           \_ gdb --batch --eval-command=bt /proc/3480/exe 3480
 3785 12:50                          |           \_ sed -n -e s,\x1B\[[0-9;]*[a-zA-Z],,g -e s/^(gdb) // -e /^#/p -e /^   /p -e s/\(^Thread.*\)/@\1/p
 3786 12:50                          |           \_ tr @ \n
 3492 12:50                          \_ python /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_X_2017-07-31-1200/bin/slc6_amd64_gcc630/compare_using_files.py /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/files/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_ 
 3734 12:50                          |   \_ sh -c /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/lcg/root/6.10.02/etc/gdb-backtrace.sh 3492 1>&2
 3741 12:50                          |       \_ /bin/sh /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/lcg/root/6.10.02/etc/gdb-backtrace.sh 3492
 3780 12:50                          |           \_ gdb --batch --eval-command=bt /proc/3492/exe 3492
 3781 12:50                          |           \_ sed -n -e s,\x1B\[[0-9;]*[a-zA-Z],,g -e s/^(gdb) // -e /^#/p -e /^   /p -e s/\(^Thread.*\)/@\1/p
 3782 12:50                          |           \_ tr @ \n
 3503 12:50                          \_ python /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_X_2017-07-31-1200/bin/slc6_amd64_gcc630/compare_using_files.py /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/files/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_ 
 3713 12:50                              \_ sh -c /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/lcg/root/6.10.02/etc/gdb-backtrace.sh 3503 1>&2
 3720 12:50                                  \_ /bin/sh /cvmfs/cms-ib.cern.ch/nweek-02483/slc6_amd64_gcc630/lcg/root/6.10.02/etc/gdb-backtrace.sh 3503
 3775 12:50                                      \_ gdb --batch --eval-command=bt /proc/3503/exe 3503
 3776 12:50                                      \_ sed -n -e s,\x1B\[[0-9;]*[a-zA-Z],,g -e s/^(gdb) // -e /^#/p -e /^   /p -e s/\(^Thread.*\)/@\1/p
 3777 12:50                                      \_ tr @ \n

```

**Comment by slava77** [comment]
On 8/3/17 12:55 AM, Malik Shahzad Muzaffar wrote:
> @slava77 <https://github.com/slava77> , #882 (comment)
> <https://github.com/cms-sw/cms-bot/pull/882#issuecomment-319857333>


> should limit the parallel jobs to N (where N is number of processors)

I'm missing a change in the code. (the link is to the text comment in
this PR itself)
Please point me more directly.
Thank you.

**Comment by smuzaffar** [comment]
oops, wrong link was pasted there. Change is accessible here
https://github.com/cms-sw/cms-bot/commit/509e4b42dd643b6d0d85aa415e3703b7da78349f#diff-46d8499566ca1320f3be0ff31cb4441f

**Comment by slava77** [comment]
On 8/3/17 6:42 AM, Malik Shahzad Muzaffar wrote:
> oops, wrong link was pasted there. Change is accessible here
> 509e4b4#diff-46d8499566ca1320f3be0ff31cb4441f
> <https://github.com/cms-sw/cms-bot/commit/509e4b42dd643b6d0d85aa415e3703b7da78349f#diff-46d8499566ca1320f3be0ff31cb4441f>
> 

thanks.

the problem with the deafult comparisons is that it starts multiple threads.
So, it will likely not help to reduce the load in full.

**Pull request merged**
