### PR TITLE
Changed name for DQM/Phase2OuterTracker 

### PR DESCRIPTION
**Pull request by emacdonald16**
Changed name from DQM/Phase2OuterTracker-> DQM/SiOuterTracker; added Validation/SiOuterTrackerV
For pull request: https://github.com/cms-sw/cmssw/pull/22682
(pull request shows different name, but will be modifying name soon)

### CODE REVIEW

**Comment by smuzaffar** [comment]
-externals
@emacdonald16,  DQM/Phase2OuterTracker package exists in other release cycles too (84X and above). So we can not remove it.  If DQM/SiOuterTracker is acceptable to dqm then just add the new package.

**Comment by emacdonald16** [comment]
@smuzaffar Can you please check again for externals?

**Comment by smuzaffar** [comment]
assign dqm

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
