### PR TITLE
reco comparisons: nanoAOD and MTD plot updates

### PR DESCRIPTION
**Pull request by slava77**
- MTD
    - fix time error variable accessor name (```timeError```) for FTLClusters
    - drop nonexistent value (transient) plotting of positions in mtdTrackingRecHits
    - add plots of BTL and ETL chi2 matches with tracks
- NANO
    - update the list of plotted tables to the full list available as of CMSSW_11_2_X_2020-06-18-1100

the comparisons on jenkins tests are expected to run and return no differences on "self"-comparisons

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mrodozov** [comment]
if you say its fine we merge it

**Comment by slava77** [comment]
> if you say its fine we merge it

I checked the logs and they look as expected from the changes made in this PR.
So, please go ahead with merging.
Thank you.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
