### PR TITLE
Added l1scouting category

### PR DESCRIPTION
**Pull request by Mmiglio**
Added a new `l1scouting` category, introduced in the PR cms-sw/cmssw#43467. 
I'm not sure whether I can proceed with this PR or if I should wait for a formal request on the other PR.
Tagging @emeschi and @smorovic

### CODE REVIEW

**Comment by smuzaffar** [comment]
@Mmiglio , is there no existing category (e.g. `daq` or `l1`) who should be responsible for these new packages?

**Comment by makortel** [comment]
> is there no existing category (e.g. `daq` or `l1`) which should be responsible for these new packages?

Let me tag @cms-sw/daq-l2 and @cms-sw/l1-l2 too. I think we'd need clear motivation to add a new signatory category.

**Comment by aloeliger** [comment]
@Mmiglio Are there dedicated offline software conveners for l1Scouting? Is there an L1 scouting group operating in parallel to L1 that I am unaware of, or is this project managed under L1?

**Comment by emeschi** [comment]
@aloeliger indeed the l1 scouting is part of the l1 project. I think it is perfectly fine if you and Enrique are willing to take care of the approval chain. It was me who actually suggested creating a new category since the l1 scouting, while being part of the trigger, does not participate in the trigger chain and is not acquired by the central daq, but has its own separate acquisition chain. For this reason, it may be convenient to keep it in a separate category, but I don't think anybody feels strongly about that. We can, if you wish, discuss this directly (in person or otherwise). @makortel we could indeed also put the code under the daq category, which would probably be more appropriate than l1 for the reasons stated above. Anyone of the three is okay with us.

**Comment by emeschi** [comment]
Hello! Any news on this one ? As mentioned previously, we would be happy with any solution as long as this allows us to proceed with the actual PR for the code

**Comment by smuzaffar** [comment]
I am fine with adding these packages under `daq`. If no objections for `l1` (@cms-sw/l1-l2 ) then @Mmiglio please update the PR

**Comment by aloeliger** [comment]
No objections over here for this to go in DAQ.

**Pull request merged**
