### PR TITLE
Comparisons update: matrix map updates and add several new collections to monitor

### PR DESCRIPTION
**Pull request by slava77**
- Matrix map
    - add 2023 workflow names
    - update 1001.0 name to resolve issues as in https://github.com/cms-sw/cmssw/pull/14640#issuecomment-221807431
- fwlite based comparisons added monitoring for several collections (all are small or fast; comparisons time should not increase much)
    - add cosmicDCTracks (very new) and displacedGlobalMuons (was a round for a while) 
    - add basic hcalDigis monitoring (just look at the size per event)

### CODE REVIEW

**Comment by slava77** [comment]
@smuzaffar @degano 
please check this

Thanks.

**Comment by smuzaffar** [comment]
@slava77 , do you want us to revert it?

**Comment by slava77** [comment]
sorry, it was merged already. I must have not reloaded the page properly

**Comment by slava77** [comment]
no need to revert. 
it just looked still unmerged on the page state I was looking at.

**Pull request merged**
