### PR TITLE
attempt at making product size comparisons

### PR DESCRIPTION
**Pull request by jpata**
Address #1396 by pulling in Slava's compareProducts script and try to run it in the PR comparisons. This is a first attempt at trying to run this in the test infra, so likely things are not done in the best possible way - suggestions welcome!

### CODE REVIEW

**Comment by jpata** [comment]
please test

**Comment by smuzaffar** [comment]
@jpata , the comparison failed 
```
17:41:41 + mkdir compareProducts
17:41:41 + cd compareProducts
17:41:41 + cp /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/cms-bot/comparisons/compareProducts.awk /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/cms-bot/comparisons/compareProducts.sh ./
17:41:41 + ./compareProducts.sh '/data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-260491/23434.21_TTbar_14TeV+*2026D49PU*ProdLike*/step3.root' '/data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/CMSSW_11_2_X_2020-10-27-2300/23434.21_TTbar_14TeV+*2026D49PU*ProdLike*/step3.root'
17:41:41 + ERR=17
```

**Comment by jpata** [comment]
Can you give a hint where I could see this log and how to debug this further? I didn't find the output in the jenkins [log](https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/10338/consoleText) or the output [folder](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-260491/10338/). Most likely I'm not looking in the right place.

Thanks!

**Comment by smuzaffar** [comment]
@jpata , I have updated the PR ( https://github.com/cms-sw/cms-bot/pull/1408/commits/98a1a3a4dbc52ccacf72e62acd5f5092f889c6fb ) to not fail. This will allow to upload the products.log log which you can check to see why it failed

**Comment by smuzaffar** [comment]
please test

**Comment by jpata** [comment]
Thank you!

**Comment by jpata** [comment]
It didn't find the step3 output:
```
/data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-260491/23434.21_TTbar_14TeV+*2026D49PU*ProdLike*/step3.root does not exist
```
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-10-28-2300+260491/39639/products.log

Need to look into it...

**Comment by smuzaffar** [comment]
let me manually restart the comparison job

**Comment by jpata** [comment]
thank you!

**Comment by jpata** [comment]
Looks like it's working: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-10-28-2300+260491/39654/products.log

As there are no differences, it reports nothing.
```
Checking process _RECO /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-260491/23434.999_TTbar_14TeV+2026D49PU_PMXS1S2PR+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU/step3.root and /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/CMSSW_11_2_X_2020-10-28-2300/23434.999_TTbar_14TeV+2026D49PU_PMXS1S2PR+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU/step3.root with useUnpacked=no (if above 100 or 20%):
<EOF>
```

@slava77 et al, do you think this workflow makes sense for a size check? Should we also add MINIAOD?

**Comment by slava77** [comment]
> 23434.999_ ... 
> @slava77 et al, do you think this workflow makes sense for a size check? Should we also add MINIAOD?

it's better than nothing; the workflow is only PU50. I'd rather we check the outputs of the workflow used in "enable profiling". That's for phase-2.

We need similar checks for pre-phase-2.

**Comment by slava77** [comment]
> Looks like it's working: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-10-28-2300+260491/39654/products.log

I'd update the arguments from the defaults, change the process name to `_` to include everything and put a smaller threshold, perhaps at 10% instead of 20%.

**Comment by jpata** [comment]
> it's better than nothing; the workflow is only PU50. I'd rather we check the outputs of the workflow used in "enable profiling". That's for phase-2.

Right. Profiling is rather slow (recently jobs were timing out after 24h), but I think we should figure out a way to run size checks as well as some basic profile for every nontrivial PR. I'm fine to run this concurrently with profiling, but we should find a way to make the profiling turnaround a bit faster so that we can nearly always run it.

> I'd update the arguments from the defaults, change the process name to _ to include everything and put a smaller threshold, perhaps at 10% instead of 20%.

good point!

**Comment by smuzaffar** [comment]
@jpata , you need to fix this error  ( https://cmssdt.cern.ch/jenkins/job/compare-root-files-short-matrix/39654/consoleText )
```
awk: fatal: can't open source file `comparisons/compareProducts.awk' for reading (No such file or directory)
```

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
hmm, I'm confused.. I can no longer find the compareProducts output in the [summary](https://github.com/cms-sw/cms-bot/pull/1408#issuecomment-720742776), and the jenkins log referred to by https://github.com/cms-sw/cms-bot/pull/1408#issuecomment-720666307 is empty too.
@smuzaffar could you give me some advice? thx!

**Comment by smuzaffar** [comment]
@jpata , cpmpareProducts are avaiable via comparison results (as these are run as part of comparison job) e.g. go to https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-260491/10448/summary.html and then click on "See Comparison Results" ( https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-11-02-1100+260491/39684/ ) and there you will find these logs.

**Comment by jpata** [comment]
Thanks! I'm not sure how I missed this. Anyway, now looks like it's really working and producing outputs...

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-11-02-1100+260491/39684/products_AOD.log
```
Checking process _ /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-260491/136.874_RunEGamma2018C+RunEGamma2018C+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Offline_L1TEgDQM+HARVEST2018_L1TEgDQM/step3.root and /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/CMSSW_11_2_X_2020-11-02-1100/136.874_RunEGamma2018C+RunEGamma2018C+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Offline_L1TEgDQM+HARVEST2018_L1TEgDQM/step3.root with useUnpacked=no (if above 100 or 10%):
Compare packed values
-----------------------------------------------------------------
   or, B         new, B      delta, B   delta, %   deltaJ, %    branch 
-----------------------------------------------------------------
-------------------------------------------------------------
  2744267 ->     2744267          0             0.0     ALL BRANCHES

```

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-11-02-1100+260491/39684/products_MINIAOD.log
```
Checking process _ /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-260491/136.874_RunEGamma2018C+RunEGamma2018C+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Offline_L1TEgDQM+HARVEST2018_L1TEgDQM/step3_inMINIAOD.root and /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/CMSSW_11_2_X_2020-11-02-1100/136.874_RunEGamma2018C+RunEGamma2018C+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Offline_L1TEgDQM+HARVEST2018_L1TEgDQM/step3_inMINIAOD.root with useUnpacked=no (if above 100 or 10%):
Compare packed values
-----------------------------------------------------------------
   or, B         new, B      delta, B   delta, %   deltaJ, %    branch 
-----------------------------------------------------------------
-------------------------------------------------------------
    55709 ->       55709          0             0.0     ALL BRANCHES
```

Per the discussion with Slava, we should also enable this for the igprof workflow, I'll do that next.

**Comment by jpata** [comment]
If I want to run compareProducts also when igprof is run, should it be put here? https://github.com/cms-sw/cms-bot/blob/master/pr_testing/test_multiple_prs.sh#L1177
It seems to me that https://github.com/cms-cmpwg/profiling.git that is used there also includes compareProducts in some fashion, so perhaps this is already in the works.

@gartung @smuzaffar can you give some hints what would be the best way to enable compareProducts for profiling workflows? Thanks!

**Comment by gartung** [comment]
There is a compareProducts that Jiwoon ran by hand for each pre-release. I never automated that part. 
I could use your wrapper shell script, I just need to know where to get the baseline root files for comparison. The root files generated are output to $WORKSPACE by passing --dirin and --dirout to runTheMatrix.py.
https://github.com/cms-cmpwg/profiling/blob/9c442c775989bf4e6afacb0f0db36858d7231df2/Gen_tool/Gen.sh#L55
The workflow is 23434.21 for the profiling part of the PR tests. Are there baseline root files for this workflow?

**Comment by gartung** [comment]
This is the script that run igprof on nightly integration builds and the line where the RECO event loop file is generated.
https://github.com/cms-sw/cms-bot/blob/d35d7eeaf891a83d645aa2f1c3e7463a2f20ecb7/run-ib-igprof#L30
You could add the comparison here.

**Comment by jpata** [comment]
> The workflow is 23434.21 for the profiling part of the PR tests. Are there baseline root files for this workflow?

Good point, it doesn't look like there's a baseline for 23434.21 in the IB-s. However, I suppose there must be a profiling baseline?

I'm looking through the run-ib-igprof script (thx for the reference), but I can't quite tell where the baseline-to-PR profiling comparison is being run. I suppose that would be the easiest location to do a comparison of the old step3.root and new step3.root for the workflow 23434.21. Any tips are appreciated!

**Comment by gartung** [comment]
> Good point, it doesn't look like there's a baseline for 23434.21 in the IB-s. However, I suppose there must be a profiling baseline?

There is not one stored on cmssdt. Jiwoon has all of the files stored locally for the pre-release comparisons.

**Comment by jpata** [comment]
Per a private discussion with Patrick, the profiling comparison is run with respect to text files generated by the IB, the root files are not stored. I'll try this suggestion from him:
> You could add lines 33-41 of compareProducts.sh at line 30 of cms-bot/run-ib-igprof and save the outputs to files.

**Comment by jpata** [comment]
Following further discussion, @gartung offered to implement the size comparison for profiling tests. We would need to merge this PR first to have the compareProducts scripts available.

@smuzaffar et al would this be OK for you?

**Comment by jpata** [comment]
I must have misunderstood, we want to merge #1413 and #1414 first, and then do the comparison in this PR.

**Comment by gartung** [comment]
@jpata https://github.com/cms-sw/cms-bot/pull/1414 does need to go in first to get the sizes files generated for each IB. https://github.com/cms-sw/cms-bot/pull/1413 needs to be merged after yours because it makes use of your awk and shell scripts when profiling is enabled in a pull request. If you want to add the comparisons you would also need to run wf 23434.21 to get the sizes for comparison.

**Comment by gartung** [comment]
Or https://github.com/cms-sw/cms-bot/pull/1413 can be merged first and you can add 23434.21 to the comparison tests.

**Comment by gartung** [comment]
It looks like the root files for wf 23434.21 are already generated.
https://github.com/cms-sw/cms-bot/blob/4246a43c713ffbdd55a454674401a644488feb70/comparisons/matrix_RE.txt#L841

**Comment by jpata** [comment]
Thanks @gartung! Since you already integrated all the changes in this PR to #1413, we could just close this PR here and go forward with #1413 (as it also has a fix to compare txt files instead of root files). I think everything should be in place now to get size comparisons for the profiling workflows, as well as for standard workflows?

**Comment by gartung** [comment]
Yes I think that is correct.

**Comment by smuzaffar** [comment]
ok closing it then :-)

**Pull request closed without merging**
