### PR TITLE
Generate baseline ref for extra workflows of PR

### PR DESCRIPTION
**Pull request by smuzaffar**
<cmsbot></cmsbot>

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- workflows = 250202.1,250202.171,250202.181,250206.181

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
was there a replacement for this PR?
it would be nice to be able to run comparisons for extra workflows.

**Pull request closed without merging**
