### PR TITLE
switch between AutoLibraryLoader::enable() and FWLiteEnabler::enable()

### PR DESCRIPTION
**Pull request by vlimant**
taking a stab at the last comment in #1886

### CODE REVIEW

**Comment by smuzaffar** [comment]
thanks @vlimant , looks good. Can you please also update https://github.com/cms-sw/cms-bot/blob/master/comparisons/validateJR.py#L45 ?

**Comment by vlimant** [comment]
indeed ...

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_5_3_X

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
