### PR TITLE
Change DAQ L2 from mommsen to smorovic

### PR DESCRIPTION
**Pull request by mommsen**
As I will leave CMS by the end of September, I would like to assign Srecko Morovic as DAQ L2 in my place.

### CODE REVIEW

**Comment by smuzaffar** [comment]
any objections @smorovic, @silviodonato, @dpiparo, @qliphy ?

**Comment by smorovic** [comment]
@smuzaffar, from my side no objections.

**Comment by qliphy** [comment]
@smuzaffar fine with me.

**Comment by silviodonato** [comment]
ok from my side

**Pull request merged**
