### PR TITLE
reco comparisons: bugfix for the map for OldDigi_2026D49 and add FTLRecHit position plot

### PR DESCRIPTION
**Pull request by slava77**
- recently added mapping for wf 23234.1001 had a wrong file name; fixed here
- cms-sw/cmssw#29803 has a new variable useful for monitoring; added here

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

to confirm that 23234.1001 reco diff will appear in the outputs

**Comment by smuzaffar** [comment]
+externals

**Comment by silviodonato** [comment]
> @cmsbuild please test
> 
> to confirm that 23234.1001 reco diff will appear in the outputs

@slava77 the comparison test shows `Reco comparison results: 0 differences found in the comparisons`. Is it ok?

**Comment by slava77** [comment]
> @slava77 the comparison test shows `Reco comparison results: 0 differences found in the comparisons`. Is it ok?

this summary is for actual differences in distributions.
This PR does not modify anything produced in reco (CMSSW),
in most cases this can not introduce differences.

I was not precise in my wording, I meant that the directory for diffs will appear as it did in 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-06-02-2300+98c400/36798/validateJR/all_OldVSNew_TTbar14TeV2026D49OldDigiwf23234p1001/

**Comment by silviodonato** [comment]
+1

**Pull request merged**
