### PR TITLE
revert maxmem_profile change

### PR DESCRIPTION
**Pull request by smuzaffar**
To test https://github.com/cms-sw/cmssw/pull/45150

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw/pull/45150

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw/pull/45150

**Comment by rappoccio** [comment]
+1

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
