### PR TITLE
Create pull request posting function in its own module that can replaced in the repos directory.

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by smuzaffar** [comment]
any reason not to add this in github_utils.py?

**Comment by gartung** [comment]
You can make your own custom githhub_utils.py?

**Comment by smuzaffar** [comment]
ah ok

**Comment by smuzaffar** [comment]
please test

**Comment by gartung** [comment]
This follows the pattern of process-pull-request calling process_pr() from process_pr.py. The student was able to add his own process_pr.py in repos/Mu2e.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
