### PR TITLE
Add TICL package under upgrade

### PR DESCRIPTION
**Pull request by rovere**
See cms-sw/cmssw#26295

### CODE REVIEW

**Comment by smuzaffar** [comment]
assign upgrade

**Comment by smuzaffar** [comment]
+externels

**Comment by kpedro88** [comment]
should it go under reconstruction as well? @slava77 @perrotta

**Comment by slava77** [comment]
> should it go under reconstruction as well? @slava77 @perrotta

sure

**Comment by gudrutis** [comment]
The last cms build message was posted due to a bug in a new feature, which is in development. Please ignore.

**Pull request merged**
