### PR TITLE
Add sqlite file for MEM_LIVE report for IB and PR testing.

### PR DESCRIPTION
**Pull request by gartung**
Using options show on this page
https://igprof.org/analysis.html

### CODE REVIEW

**Comment by gartung** [comment]
@makortel can you start the test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by gartung** [comment]
@smuzaffar How can this be tested with the IB igprof job.

**Comment by smuzaffar** [comment]
just update the jenkins job to use your branch and trigger a job for couple of days old IB.

**Comment by gartung** [comment]
@smuzaffar This is working as expected now. Once this is merge I will switch the job back to using cmssw/cms-bot/master.

**Pull request merged**
