### PR TITLE
Add Thomas Reis and Nick Smith to L1T L2 list

### PR DESCRIPTION
**Pull request by abrinke1**
The L1T group (Alex Tapper, Emmanuel Perez, Vladimir Rekovic, Alex Zabi, and myself) would like to request adding Thomas Reis (@thomreis) and Nick Smith (@nsmith-) to the CMSSW_L2 list.  They are responsible for L1T code (unpackers, emulators, DQM) related to the Muon and Calorimeter triggers.

### CODE REVIEW

**Comment by smuzaffar** [comment]
@davidlange6 and @rekovic any objections?

**Comment by davidlange6** [comment]
just to clarify - the idea is that @nsmith and @thomreis will now do code review of general L1 PRs and triaging of L1 problems that are pending in cmssw issues? (where @rekovic is quite behind) -

**Comment by abrinke1** [comment]
@davidlange6 The idea is to have them help out where and when they can.  @nsmith and especially @thomreis already do a good bit of L1T code review and debugging, and this will help them expedite the process of solving L1T code problems, as well as streamlining the integration of small, simple PRs that can get backlogged.

**Comment by davidlange6** [comment]
Thanks - could we remove Mike (Mulhearn) at the same time?

**Comment by abrinke1** [comment]
@davidlange6 This is already included in the PR as well, if no one objects ...

**Comment by nsmith-** [comment]
Sorry to `nsmith` who is Nathan Smith and appears wholly unconnected to this. :(
I have a dash: `nsmith-`
Why do I have a dash? I don't remember anymore

**Comment by davidlange6** [comment]
Apologies!

But then the pr needs to be fixed. I’ll do it in a few hours if no one does before

Cheers,
David


On 29 Nov 2017, at 12:36, Nicholas Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry to nsmith who is Nathan Smith and appears wholly unconnected to this. :(
I have a dash: nsmith-
Why do I have a dash? I don't remember anymore

**Comment by davidlange6** [comment]
thanks @smuzaffar

**Pull request merged**
