### PR TITLE
Revert "Add TimeMemorySummary.py as default option for every runTheMatrix.py workflow"

### PR DESCRIPTION
**Pull request by fabiocos**
Reverts cms-sw/cms-bot#1112

### CODE REVIEW

**Comment by fabiocos** [comment]
@smuzaffar unfortunately this is breaking some tests where customisation is already added

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by smuzaffar** [comment]
I am reverting it from now as it  is causing problems during PR tests

```
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_X_2019-04-05-1100/bin/slc7_amd64_gcc700/cmsDriver.py", line 56, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_X_2019-04-05-1100/bin/slc7_amd64_gcc700/cmsDriver.py", line 28, in run
    configBuilder.prepare()
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_X_2019-04-05-1100/python/Configuration/Applications/ConfigBuilder.py", line 2251, in prepare
    self.pythonCfgCode += self.addCustomise()
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_X_2019-04-05-1100/python/Configuration/Applications/ConfigBuilder.py", line 860, in addCustomise
    raise Exception("cannot specify twice "+fcn+" as a customisation method") 
Exception: cannot specify twice customise as a customisation method
```
because the cmooand it tried to run had two customize
```
cmsDriver.py SingleElectronE120EHCAL_pythia8_cfi  --conditions auto:run1_mc -n 10 --eventcontent FEVTDEBUG --relval 25000,250 -s GEN,SIM,DIGI,DIGI2RAW,RAW2DIGI,L1Reco,RECO,EI --datatier GEN-SIM-DIGI-RAW-RECO --beamspot NoSmear --customise Validation/Configuration/ECALHCAL.customise,SimGeneral/MixingModule/fullMixCustomize_cff.setCrossingFrameOn --customise Validation/Performance/TimeMemorySummary.py --fileout file:step1.root  --suffix "-j JobReport1.xml "  > step1_SingleElectronE120EHCAL+SingleElectronE120EHCAL.log
```

**Comment by fabiocos** [comment]
```
cmsDriver.py SingleElectronE120EHCAL_pythia8_cfi  --conditions auto:run1_mc -n 10 --eventcontent FEVTDEBUG --relval 25000,250 -s GEN,SIM,DIGI,DIGI2RAW,RAW2DIGI,L1Reco,RECO,EI --datatier GEN-SIM-DIGI-RAW-RECO --beamspot NoSmear --customise Validation/Configuration/ECALHCAL.customise,SimGeneral/MixingModule/fullMixCustomize_cff.setCrossingFrameOn,Validation/Performance/TimeMemorySummary.customiseWithTimeMemorySummary --fileout file:step1.root  --suffix "-j JobReport1.xml "
```

just works, so one needs to use the string "--customise Validation/Performance/TimeMemorySummary.customiseWithTimeMemorySummary" as argument to --command, after checking whether this is already present, in which case the string ",Validation/Performance/TimeMemorySummary.customiseWithTimeMemorySummary" needs to be appended

**Pull request merged**
